### PR TITLE
close sqlite connections again

### LINKED ISSUE #1921: gitsync22.sc.test-watches EXCEPTION!!!: SQLite3 returned ErrorCan'tOpen while attempting to perform open "blahblah/unison.sqlite3"
The log:
```
⚙  git init --bare /private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/git-simple-5e5164ecfeec6464/repo.git

⚙️   Processing stanza 1 of 3.
⚙️   Processing stanza 2 of 3.
⚙️   Processing stanza 3 of 3.  Downloading from /private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/git-simple-5e5164ecfeec6464/repo.git ...
warning: --depth is ignored in local clones; use file:// instead.
warning: You appear to have cloned an empty repository.
                                                                                                                    
  Downloading from /private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/git-simple-5e5164ecfeec6464/repo.git ...
warning: --depth is ignored in local clones; use file:// instead.
warning: You appear to have cloned an empty repository.
                                                                                                                    
  Staging files for upload to /private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/git-simple-5e5164ecfeec6464/repo.git ...
Synced 225 entities.
Done syncing 225 entities.[?25h
Done syncing 225 entities.[?25h                                                                                                                               
  Uploading to /private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/git-simple-5e5164ecfeec6464/repo.git ...
                                                                                                                
  [0m[31m _____[0m[93m     _             [0m
  [0m[31m|  |  |[0m[91m___[0m[93m|_|[0m[92m___ [0m[36m___ [0m[35m___ [0m
  [0m[31m|  |  |   [0m[93m| |[0m[92m_ -[0m[36m| . |[0m[35m   |[0m
  [0m[31m|_____|[0m[91m_|_[0m[93m|_|[0m[92m___[0m[36m|___|[0m[35m_|_|[0m
  
  Running the provided transcript file...
  
[0m

⚙️   Processing stanza 1 of 1.  Downloading from /private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/git-simple-5e5164ecfeec6464/repo.git ...
warning: --depth is ignored in local clones; use file:// instead.
                                                                                                                    
  Importing downloaded files into local codebase...
gitsync22.sc.test-watches EXCEPTION!!!: SQLite3 returned ErrorCan'tOpen while attempting to perform open "/private/var/folders/gg/lqv4nxmx0nv3_35tg9_8c15r0000gn/T/ucm-test-538c8ee21b65ab4b/.unison/v2/unison.sqlite3": unable to open database file
💥  gitsync22.sc.test-watches
```
However when I run the test in isolation it passes.  When I try to open the database file manually, it opens.

Perhaps we are running out of database connections. 🤦   Except... why did it pass on github CI?  Maybe the limits are different?

- [ ] Could try changing the order of the tests and seeing if that changes which test fails first.

### LINKED ISSUE #1922: smartly release sqlite database connections
Ucm keeps a lot of monadic/lazy references to stuff in memory, which makes it hard to know when to close database connections.  It can also run out of file handles after a certain number of operations, and although this situation can be improved by increasing the number of handles (defaults to 256 on my machine).

I don't think we should continue lazily pulling definitions out of wherever, that probably using reader to pass a codebase or some descriptor would be better, but open to alternatives.

This is a solution to #1921

### PR DESCRIPTION
**Pull request by aryairani**
## Overview

Adds/restores the idea of closing open codebases. It tries to finish using and then close external codebases as quickly as possible.

Closes #1922, and with #1929 should fix #1921.

## Implementation notes

It modifies `Init.createCodebase`, `Init.openCodebase`,  and `Codebase.viewRemoteBranch'` to return an extra `m ()` / `IO ()` action that should be used to close resources that are supporting an open codebase.

The helpers `Init.createCodebaseOrError`, `Init.CreateCodebaseOrError'`, `Codebase.getCodebaseOrExit`, `Codebase.openNewUcmCodebaseOrExit` also return the cleanup action.

## Test coverage

I haven't added any new tests for this, but I'm running `Unison.Test.BaseUpgradePushPullTest` (slow, not part of CI), as I write this, and that seems like it should be pretty thorough.  I guess I could make it part of CI.

### CODE REVIEW

File: parser-typechecker/src/Unison/Codebase/FileCodebase.hs [hunk 1]
```diff
@@ -94,10 +94,11 @@ import UnliftIO.STM (atomically)
 
 init :: (MonadIO m, MonadCatch m) => Codebase.Init m Symbol Ann
 init = Codebase.Init
-  openCodebase
-  createCodebase
+  ((fmap . fmap) (pure (),) . openCodebase)
+  ((fmap . fmap) (pure (),) . createCodebase)
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/Codebase/FileCodebase.hs:98]: Needs moar `fmap`

**Review by pchiusano — APPROVED** [review]

File: parser-typechecker/src/Unison/Codebase/FileCodebase.hs (hunk 1 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/FileCodebase.hs:98]: I know, right?

**Comment by aryairani** [comment]
No crashes; but I'm having a hard time reproducing crashes on old builds too, so I don't 100% know what's up.
