### PR TITLE
Replace sqlite-simple with unison-sqlite

### LINKED ISSUE #2622: ucm should gracefully handle a locked sqlite db
for our current experiments with unison cloud, we are finding ourselves running multiple ucm processes against the same codebase at the same time. For the most part this works, but sometimes it seems that two of them try to lock the DB at the same time, which results in the loser crashing with an error:

    Exception: SQLite3 returned ErrorBusy while attempting to perform step: database is locked

It would be great if we could recover from these errors, since restarting ucm takes a long time with our current codebase

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

This PR:

- Removes direct usage of `sqlite-simple`/`direct-sqlite` in favor of `unison-sqlite`, which wraps them, but exports a nicer interface with a `Transaction` abstraction, much better query logging and error-throwing functionality (including full context of query, params, and results, where appropriate), and will (eventually) house improvements like the #2717.
- Fixes #2622 

A number of associated changes were also made along the way. Initially I considered separating each change into its own PR wherever possible, but decided against that as they continued to pile up, and are all related to swapping out the database layer to use `Transaction` anyway.

- I simplified `lca` to only use a single database connection, rather than two, since it's fine to interleave steps through two statement objects, as the `lca` algorithm does.
- I added a number of new helpers to `unison-sqlite` itself, like `runReadOnlyTransaction` and `runWriteTransaction`, as well as `queryStreamRow` to support `lca`, which only reads as many rows as it needs to.
- I improved the query logging when `UNISON_DEBUG=` is set.
- I deleted `Unison.Sqlite.DB` as it's no longer used. Now, there's just the raw `Connection` interface and the preferred higher-level `Transaction` interface.
- I added a `callStack` field to sqlite exceptions to aid in debugging (it only works if running a profiled build).
- I extracted many database operations underlying the sqlite codebase abstraction to the top level of a new `Unison.Codebase.SqliteCodebase.Operations` module. This was necessary to decouple the codebase abstraction from the codebase migrations.
- I did all of the necessary simplification/refactoring to the sync algorithm and migrations to support the new underlying database layer.
- I set the default uncaught exception handler to one that pretty-shows the exception.

Here's an example of the logging you see (with `UNISON_DEBUG=` set):
Screen Shot 2022-04-01 at 11 08 23 AM

Here's an exception induced by a SQL typo:

Screen Shot 2022-04-01 at 11 22 30 AM

And a decoder error:

Screen Shot 2022-04-01 at 11 39 35 AM

(Those `callStack = []` get filled out if you build with `stack build --profile`).

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Small TODO: make `executeMany` do less work on `[]`

**Review by aryairani — APPROVED** [review]

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs [hunk 1]
```diff
@@ -61,49 +56,57 @@ data DecodeError
...
-  { srcDB :: Connection,
-    destDB :: Connection,
+data Env m = Env
+  { runSrc :: forall a. Transaction a -> m a,
+    runDest :: forall a. Transaction a -> m a,
     -- | there are three caches of this size
     idCacheSize :: Word
   }
 
+mapEnv :: (forall x. m x -> n x) -> Env m -> Env n
```
Comment (ChrisPenner) [inline codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs]: Nit: It really doesn't matter, but I've been using the name `hoist`, e.g. `hoistEnv` for natural transformations in other places as best I can to make them easier to find and differentiate them from "fmap"-y things.

File: lib/unison-sqlite/src/Unison/Sqlite/Connection.hs [hunk 2]
```diff
@@ -176,18 +211,43 @@ queryListRow conn@(Connection _ _ conn0) s params =
...
   where
-    doQueryListRow = do
-      debugM Debug.Sqlite "query" s
-      debugM Debug.Sqlite "params" (anythingToString params)
-      result <- run
-      debugM Debug.Sqlite "result" (anythingToString params)
-      debugLogM Debug.Sqlite "----------"
-      pure result
-    run = Sqlite.query conn0 (coerce s) params
+    thing =
```
Comment (ChrisPenner) [inline lib/unison-sqlite/src/Unison/Sqlite/Connection.hs]:
```suggestion
    runStatement =
```

File: lib/unison-sqlite/src/Unison/Sqlite/Connection.hs [hunk 3]
```diff
@@ -165,9 +200,9 @@ execute_ conn@(Connection _ _ conn0) s = do
 
 -- With results, with parameters, without checks
 
-queryListRow :: (Sqlite.FromRow b, Sqlite.ToRow a) => Connection -> Sql -> a -> IO [b]
-queryListRow conn@(Connection _ _ conn0) s params =
-  doQueryListRow `catch` \(exception :: Sqlite.SQLError) ->
+queryStreamRow :: (Sqlite.FromRow b, Sqlite.ToRow a) => Connection -> Sql -> a -> (IO (Maybe b) -> IO r) -> IO r
+queryStreamRow conn@(Connection _ _ conn0) s params callback =
+  thing `catch` \(exception :: Sqlite.SQLError) ->
```
Comment (ChrisPenner) [inline lib/unison-sqlite/src/Unison/Sqlite/Connection.hs]:
```suggestion
  runStatement `catch` \(exception :: Sqlite.SQLError) ->
```

File: lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs [hunk 4]
```diff
@@ -72,33 +81,110 @@ newtype Transaction a
...
-    rollback =
-      Connection.execute_ conn "ROLLBACK"
 
-    ignoringExceptions :: IO () -> IO ()
-    ignoringExceptions action =
-      action `catchAny` \_ -> pure ()
+-- | Perform IO inside a transaction, which should be idempotent, because it may be run more than once.
+-- FIXME rename to unsafeIO or something
+unsafeIO :: IO a -> Transaction a
+unsafeIO action =
```
Comment (ChrisPenner) [inline lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs:188]: `unsafeIO` implies to me that it's something like `unsafePerformIO`; would something like `liftRepeatableIO` or `liftIdempotentIO` be clearer? It's not 'unsafe' to run IO in a transaction, it's just important that the IO be safely repeatable 😄

File: lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs [hunk 5]
```diff
@@ -72,33 +81,110 @@ newtype Transaction a
...
+  action
+
+-- | Perform an atomic sub-computation within a transaction; if it returns 'Left', it's rolled back.
+savepoint :: Transaction (Either a a) -> Transaction a
+savepoint (Transaction action) = do
+  Transaction \conn -> do
+    -- Generate a random name for the savepoint, so the caller isn't burdened with coming up with a name. Seems
+    -- extremely unlikely for this to go wrong (i.e. some super nested withSavepoint call that ends up generating the
+    -- same savepoint name twice in a single scope).
+    name <- Text.pack <$> replicateM 10 (Random.randomRIO ('a', 'z'))
```
Comment (ChrisPenner) [inline lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs:175]: What do you think of accepting a name from the caller and suffixing it with a random string so that any savepoint errors will contain a human-readable name? I'm not sure it's necessary, but sqlite errors aren't always the nicest to read so it might help with debugging.

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 6]
```diff
@@ -183,93 +158,27 @@ initSchemaIfNotExist path = liftIO do
   unlessM (doesDirectoryExist $ makeCodebaseDirPath path) $
     createDirectoryIfMissing True (makeCodebaseDirPath path)
   unlessM (doesFileExist $ makeCodebasePath path) $
-    withConnection "initSchemaIfNotExist" path $ runReaderT Q.createSchema
+    withConnection "initSchemaIfNotExist" path \conn ->
+      Sqlite.runTransaction conn Q.createSchema
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:162]: @mitchellwrosen what influences the decision to pick `runWriteTransaction` in some spots and `runTransaction` here? I suspect we probably want to use the appropriate `read/write` version in cases where we know the type of transaction for sure?

```suggestion
      Sqlite.runWriteTransaction conn Q.createSchema
```

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 7]
```diff
@@ -290,56 +199,37 @@ sqliteCodebase debugName root localOrRemote action = do
...
-                  error $
-                    "I don't know about the builtin type ##"
-                      ++ show t
-                      ++ ", but I've been asked for it's ConstructorType."
-             in pure . fromMaybe err $
-                  Map.lookup (Reference.Builtin t) Builtins.builtinConstructorType
-          C.Reference.ReferenceDerived i -> getDeclTypeById i
+    let getTerm :: Reference.Id -> m (Maybe (Term Symbol Ann))
+        getTerm id =
+          Sqlite.runTransaction conn (CodebaseOps.getTerm getDeclType id)
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:207]:
```suggestion
          Sqlite.runReadOnlyTransaction conn (CodebaseOps.getTerm getDeclType id)
```

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 8]
```diff
@@ -290,56 +199,37 @@ sqliteCodebase debugName root localOrRemote action = do
...
-
-        getDeclComponent :: MonadIO m => Hash -> m (Maybe [Decl Symbol Ann])
-        getDeclComponent h1@(Cv.hash1to2 -> h2) =
-          runDB' conn $ map (Cv.decl2to1 h1) <$> Ops.loadDeclComponent h2
-
-        getCycleLength :: MonadIO m => Hash -> m (Maybe Reference.CycleSize)
-        getCycleLength (Cv.hash1to2 -> h2) =
-          runDB conn $ Ops.getCycleLen h2
+        getTypeOfTermImpl id =
+          Sqlite.runTransaction conn (CodebaseOps.getTypeOfTermImpl id)
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:216]:
```suggestion
          Sqlite.runReadOnlyTransaction conn (CodebaseOps.getTypeOfTermImpl id)
```

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 9]
```diff
@@ -290,56 +199,37 @@ sqliteCodebase debugName root localOrRemote action = do
...
+
+        getTermComponentWithTypes :: Hash -> m (Maybe [(Term Symbol Ann, Type Symbol Ann)])
+        getTermComponentWithTypes h =
+          Sqlite.runTransaction conn (CodebaseOps.getTermComponentWithTypes getDeclType h)
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:220]: I'll stop suggesting here, but you get the idea 😋 

```suggestion
          Sqlite.runReadOnlyTransaction conn (CodebaseOps.getTermComponentWithTypes getDeclType h)
```

**Review by ChrisPenner — APPROVED** [review]
Thanks for your work on this, looks good!

It looks good, but can you explain why the termBuffer and declBuffer were extracted and why that's part of this PR?

File: lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs (hunk 5 above)
Comment (aryairani) [reply lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs:175]: could delete this code for now

File: lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs (hunk 4 above)
Comment (aryairani) [reply lib/unison-sqlite/src/Unison/Sqlite/Transaction.hs:188]: log thing

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema1To2.hs [hunk 10]
```diff
@@ -56,127 +56,97 @@ import U.Codebase.WatchKind (WatchKind)
...
-    runDB conn . liftQ $ Q.setSchemaVersion 2
-  pure $ Right ()
+migrateSchema1To2 ::
+  -- | A 'getDeclType'-like lookup, possibly backed by a cache.
+  (C.Reference.Reference -> Sqlite.Transaction CT.ConstructorType) ->
+  TVar (Map Hash CodebaseOps.TermBufferEntry) ->
+  TVar (Map Hash CodebaseOps.DeclBufferEntry) ->
+  Sqlite.Transaction ()
+migrateSchema1To2 getDeclType termBuffer declBuffer = do
+  Sqlite.unsafeIO $ putStrLn $ "Starting codebase migration. This may take a while, it's a good time to make some tea ☕️"
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase/Migrations/MigrateSchema1To2.hs]: Maybe:

```
let log = Sqlite.unsafeIO . putStrLn
```

**Comment by aryairani** [comment]
@mitchellwrosen to do stuff with feedback and merge when ready.

File: lib/unison-sqlite/src/Unison/Sqlite/Connection.hs (hunk 2 above)
Comment (mitchellwrosen) [reply lib/unison-sqlite/src/Unison/Sqlite/Connection.hs]: I went with `run`; it's not really a statement that it's running.

**Comment by mitchellwrosen** [comment]
🤞
