### PR TITLE
Fix #1640 caused by incorrect parsing of nested patterns that mention nullary constructors

### LINKED ISSUE #1640: Spurious pattern arity mismatch error when nullary patterns are involved
```haskell
unique type Color = Red | Black
unique type RBTree a = Leaf | Tree Color (RBTree a) a (RBTree a)

RBTree.isRed = cases
  RBTree.Tree Color.Red _ _ _ -> true
  _ -> false
```

Yields this error:

```
  Sorry, you hit an error we didn't make a nice message for yet.
  
  Here is a summary of the Note:
  
    simple cause:
      PatternArityMismatch:
    loc=line 5, columns 3-30
    typ=Color -> RBTree a -> a -> RBTree a -> RBTree a
    args=1
  
    path:
      InMatch firstBody=line 5, columns 34-38
      InSynthesize e=match l13qtrrgf3 wit...
      InCheck e=match l13qtrrgf3 wit..., t=𝕣7
      InSynthesize e=cases
    RBTree.Tree ...
      InSynthesize e=let
    RBTree.isRed =...
```

### Hacky workaround

If we switch `Red` and `Black` to be unary constructors then this typechecks fine:

```haskell
unique type Color = Red () | Black ()
unique type RBTree a = Leaf | Tree Color (RBTree a) a (RBTree a)

RBTree.isRed = cases
  RBTree.Tree (Color.Red _) _ _ _ -> true
  _ -> false
```

So I'd likely stare at the pattern typechecking code and think through what happens when the pattern is nullary.

### PR DESCRIPTION
**Pull request by pchiusano**
The issue was actually in the parser, not the typechecker. A pattern like `Foo Bar a b c` was actually being parsed as `Foo (Bar a b c)`. Whoops. The pattern parser just needed to be tweaked a bit to handle this correctly. I also fixed an unreported pattern parse bug and added a test for that too.

Fixes #1640 

/cc @chiroptical

### CODE REVIEW

File: parser-typechecker/src/Unison/TermParser.hs [hunk 1]
```diff
@@ -225,15 +229,21 @@ parsePattern =
...
     tok <- ctor UnknownDataConstructor
     let (ref,cid) = L.payload tok
         f patterns vs =
           let loc = foldl (<>) (ann tok) $ map ann patterns
           in (Pattern.Constructor loc ref cid patterns, vs)
-    unzipPatterns f <$> many patternCandidates
+    unzipPatterns f <$> many leaf
 
-  seqLiteral = Parser.seq f leaf
+  seqLiteral = Parser.seq f root
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/TermParser.hs:246]: There was no reason to restrict the patterns that form the elements of a list pattern to be leaf patterns. Like `[Foo a b]` is a perfectly fine pattern but `Foo a b` is not a `leaf` pattern.

**Review by dolio — APPROVED** [review]
