### PR TITLE
Correct docs selection

### LINKED ISSUE #2759: codebase UI shows wrong docs for a hash qualified name in a relative view
Here is a term on unison share in the namespace containing that term [queried by name](https://share.unison-lang.org/latest/namespaces/iamevn/advent/year2021/day03/;/terms/main) and [queried by hash](https://share.unison-lang.org/latest/namespaces/iamevn/advent/year2021/day03/;/terms/@69dn0qqsinretcrhuvjhhfr3ue18qcvij5cv3lno22oja294et6532chuoeoknufid3ftl1kf08o168h6r8vmjasd35uubqunp6k8u0). The hash query shows docs from another term with a similar name. this term should have no docs.

They both query `/api/getDefinition` with the same parameters for `rootBranch` and `relativeTo` but differ for `names` (hashes shortened):
```
names=main
rootBranch=#rubverph...
relativeTo=iamevn.advent.year2021.day03

names=%2369dn0q...
rootBranch=#rubverph...
relativeTo=iamevn.advent.year2021.day03
```
The response for the hash query includes entries in `termDocs` where there should be none:
image

Going from the root namespace instead seems to work correctly: [query by name](https://share.unison-lang.org/latest/terms/iamevn.advent.year2021.day03.main) / [query by hash](https://share.unison-lang.org/latest/terms/@69dn0qqsinretcrhuvjhhfr3ue18qcvij5cv3lno22oja294et6532chuoeoknufid3ftl1kf08o168h6r8vmjasd35uubqunp6k8u0)

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

Our docs selection is doing two things wrong:

1. When selecting docs, it does a suffix search in the current scope, so if you load the term `html.latest.div` it will find `html.latest.lib.base.Nat.div.doc` when it shouldn't
2. It's pulling up all docs for all aliases in scope by reference, this means if you define `x = 42`, but there's also `lib.thing.foo = 42` you get the docs for _both_

closes https://github.com/unisonweb/unison/issues/2759

## Implementation notes

Here's how we fix each of the above issues:

1. When looking up the reference for the docs by name, do an _exact_ name lookup, not a suffix query.
2. Canonicalize which name we're actually looking up docs for before we construct the 'doc names', then only look up docs for the name requested by the user.

This block of code has just had a lot of bugs in it lately (and it's doing a lot) so I tried to simplify as much as I could.

Some other changes:

* add `allTermNames` and `allTypeNames` to the pretty printer
* Add `(term|type)NameOrHashOnly` to the pretty printer to simplify getting a Hash qualified name for a reference.
* Swap the definition endpoint to serve a single definition (it makes it much simpler) then just foldMapM on the layer up. It's probably slightly slower, but AFAIK we never call that endpoint with multiple terms, and it ends up simplifying the endpoint a lot. If we need to speed it up later we'd just need to pass the names in from the outer loop.

- - -
This change is [Reviewable](https://reviewable.io/reviews/unisonweb/unison/3305)

### CODE REVIEW

File: unison-share-api/src/Unison/Server/Backend.hs [hunk 1]
```diff
@@ -811,78 +810,65 @@ mungeSyntaxText ::
...
   Path ->
+  -- | The root branch to use
   Maybe (Branch.CausalHash) ->
   Maybe Width ->
+  -- | Whether to suffixify bindings in the rendered syntax
   Suffixify ->
+  -- | Runtime used to evaluate docs. This should be sandboxed if run on the server.
   Rt.Runtime Symbol ->
   Codebase IO Symbol Ann ->
-  [HQ.HashQualified Name] ->
```
Comment (ChrisPenner) [inline unison-share-api/src/Unison/Server/Backend.hs:821]: Trying to compute results for multiple terms at once makes the code more confusing and error prone, and we want to bias the printer towards each result being printed anyways, so it's likely best to do them one at a time.

Currently nobody ever calls the api with multiple terms at once anyways, and if you did it'd be tough to sort out which results are for which queries anyhow.

File: unison-share-api/src/Unison/Server/Backend.hs [hunk 2]
```diff
@@ -811,78 +810,65 @@ mungeSyntaxText ::
...
+      fqnPPE = PPED.unsuffixifiedPPE pped
   let nameSearch :: NameSearch
       nameSearch = makeNameSearch hqLength (NamesWithHistory.fromCurrentNames localNamesOnly)
-  DefinitionResults terms types misses <- lift (definitionsBySuffixes codebase nameSearch DontIncludeCycles query)
-  let width =
-        mayDefaultWidth renderWidth
-
-      namesWithFallback = localNamesOnly `Names.unionLeftRef` parseNames
-
-      termFqns :: Map Reference (Set Text)
```
Comment (ChrisPenner) [inline unison-share-api/src/Unison/Server/Backend.hs:845]: I just use the pretty printer for `termFqns` and `typeFqns` now; here is where we were finding all aliases for a reference within scope, which we don't want to do.

File: unison-share-api/src/Unison/Server/Backend.hs [hunk 3]
```diff
@@ -811,78 +810,65 @@ mungeSyntaxText ::
...
-      typeFqns = Map.mapWithKey f types
-        where
-          rel = Names.types namesWithFallback
-          f k _ =
-            Set.fromList . fmap Name.toText . toList $
-              R.lookupRan k rel
-
-      flatten = Set.toList . fromMaybe Set.empty
-
-      docNames :: Set (HQ'.HashQualified Name) -> [Name]
```
Comment (ChrisPenner) [inline unison-share-api/src/Unison/Server/Backend.hs:863]: All of the doc selection is now rolled into `docResults`

**Review by aryairani — APPROVED** [review]
Yikes. Good catch.

**Comment by ceedubs** [comment]
@hojberg @ChrisPenner has this been incorporated into Share? I just noticed that https://github.com/unisonweb/unison/issues/2759#issuecomment-1210625144 is still a problem.

**Comment by ChrisPenner** [comment]
@ceedubs  good catch, looks like Share hasn't been bumped up in a while:
https://github.com/unisoncomputing/enlil/pull/83

**Comment by ChrisPenner** [comment]
Deployed, seems to be fixed 👍🏼
