### PR TITLE
Fix typechecking of patterns for polymorphic effects

### LINKED ISSUE #693: Typechecker or runtime soundness bug in this example
Atop current unisonbase:

```Haskell
use .base
use .base.Optional
use .Pair
ability Parse where
  anyToken : Nat
  choose : '{Parse} a -> '{Parse} a -> {Parse} a
runTextParser : List Nat -> Request Parse a -> Optional a
runTextParser xs req =
  case req of
    { Parse.anyToken -> next } ->
      case xs of
        [] -> None
        (x +: xs) ->
          handle runTextParser xs in next x
    { Parse.choose l r -> next } ->
      lResult = handle runTextParser xs in !l
      case lResult of
        None -> handle runTextParser xs in !r
        Some x -> Some x
    { a } -> Some a
many : '{Parse} a -> {Parse} [a]
many p =
  unfold () '(choose '(Some (!p, ())) 'None)
bogusValue : Optional [Nat]
bogusValue =
  handle runTextParser [1,2,3] in many 'Parse.anyToken

> bogusValue
```

This returns `Some (Some (1, ()))`.

Thnaks to @zenhack for finding and minimizing this one.

### PR DESCRIPTION
**Pull request by dolio**
Fixes #693 

This actually fixes an additional problem I noticed while experimenting with the 693 example, which is that code like the following would work:

```
ability A t where
  a : t -> r

h : Request {A t} u -> u
h = cases
  { a x -> _ } -> x
  { y } -> y
```

because nothing was ensuring that `x` had type `t`, and its type was just allowed to unify with `u`. This case is covered in the test transcript.

Skolemization is done properly for data types as well, but I don't think it's possible to create a type where this matters yet.

### CODE REVIEW

File: parser-typechecker/src/Unison/Typechecker/Context.hs [hunk 1]
```diff
@@ -1369,6 +1376,35 @@ ungeneralize' (Type.Forall' t) = do
...
+  appendContext $ uctx ++ sctx
+  pure $ foldl (flip $ uncurry ABT.substInheritAnnotation) ty rn
+  where
+  fovs = forced ty
+  (uvs, svs) = partition (`Set.member` fovs) vs
+skolemize _ ty = pure ty
+
+forcedEffect :: Type v loc -> Set (TypeVar v loc)
+forcedEffect (Type.Arrow' _ o) = forcedEffect o
+forcedEffect (Type.Effect1' es _) = Type.freeVars es
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/Typechecker/Context.hs:1401]: I was thinking this wasn't quite right if arrows other than the final one have effects, but that shouldn't be a valid ability declaration (though we don't enforce that).

**Review by pchiusano — APPROVED** [review]
LGTM

File: parser-typechecker/src/Unison/Typechecker/Context.hs (hunk 1 above)
Comment (dolio) [reply parser-typechecker/src/Unison/Typechecker/Context.hs:1401]: Is that because `X ->{E} Y ->{F} Z` is represented like `Arrow X (Effect E (Arrow Y (Effect F Z)))`?

**Comment by pchiusano** [comment]
Mac build randomly failed again..

File: parser-typechecker/src/Unison/Typechecker/Context.hs (hunk 1 above)
Comment (pchiusano) [reply parser-typechecker/src/Unison/Typechecker/Context.hs:1401]: Right

Comment (dolio) [reply parser-typechecker/src/Unison/Typechecker/Context.hs:1401]: So, I was thinking about this randomly. My question is: how is this actually supposed to work? `X ->{E} Y ->{F} Z` is *not* the type of an `F` effect. It is of an `E` effect that produces a function with an `F` effect. If it is being put in the `F` ability, then that is wrong. The type checker might not prevent someone from writing it that way, but that means it is allowing something that doesn't make sense, I think.

Comment (pchiusano) [reply parser-typechecker/src/Unison/Typechecker/Context.hs:1401]: Right. It doesn't make sense. The typechecker should probably give a nice error for this.
