### PR TITLE
fix "branch already exists" error message to show project, too

### LINKED ISSUE #4494: error message for cloning an existing repository can be wrong
I made the mistake of clone a repo that I had already cloned. But the error message should have `switch @unison/advent-of-code-client/main` instead of just `switch /main`.

Ideally the fix would still omit the project name if it's within the same project.

```
nimbus/health-check> clone @unison/advent-of-code-client/main
 
  @unison/advent-of-code-client/main already exists. You can switch to it with `switch /main`.
```

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

Fixes #4494

### CODE REVIEW

File: unison-cli/src/Unison/CommandLine/OutputMessages.hs [hunk 1]
```diff
@@ -1941,7 +1941,7 @@ notifyUser dir = \case
       prettyProjectAndBranchName projectAndBranch
         <> "already exists."
         <> "You can switch to it with "
-        <> IP.makeExampleEOS IP.projectSwitch [prettyBranchName projectAndBranch]
+        <> IP.makeExampleEOS IP.projectSwitch [prettyProjectAndBranchName projectAndBranch]
```
Comment (mitchellwrosen) [inline unison-cli/src/Unison/CommandLine/OutputMessages.hs:1944]: This is the tweak; the rest is refactoring

**Comment by mitchellwrosen** [comment]
Just forgot to move this from draft last week after it passed CI

**Review by aryairani — APPROVED** [review]
