### PR TITLE
Make Codebase object thread-safe

### LINKED ISSUE #3190: Codebase Server throws 500 occasionally when using the `list` api with a `relativeTo`
Sporadically, when refreshing the local ui with a perspective the server returns a 500 for the list api (drives the sidebar).

UCM prints out the following error when this happens:

```
SqliteQueryException {sql = "BEGIN", params = "", exception = SQLite3 returned ErrorError while attempting to perform step: not an error, callStack = [], connection = Connection { name = "main", file = "/Users/hojberg/code/unison-code/.unison/v2/unison.sqlite3" }, threadId = ThreadId 497}
```

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

This PR makes the Codebase object thread-safe by making each operation use a new underlying connection to SQLite, rather than a shared connection that the Codebase closes over.

Fixes #3190, which was caused by the local UI and ucm simultaneously using the same SQLite connection.

### CODE REVIEW

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 1]
```diff
@@ -192,324 +190,351 @@ sqliteCodebase ::
...
+                }
+        Right <$> action codebase
+  where
+    withConn :: (Sqlite.Connection -> m a) -> m a
+    withConn =
+      withConnection debugName root
+
+    runTransaction :: Sqlite.Transaction a -> m a
+    runTransaction action =
+      withConn \conn -> Sqlite.runTransaction conn action
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:537]: I'm sure it's fine, but is it possible that using a single connection shared across the codebase gave us any benefits in terms of in-memory caching?

If there's anywhere we're querying the codebase in a tight-loop (there's probably at least some spots that do this) we're now acquiring a new connection for each and every query rather than using a single one.

I have no idea whether this is likely to actually cause problems in reality though 🤷🏼‍♂️

**Review by ChrisPenner — APPROVED** [review]
Nice, I'll also need this for LSP work 🙌🏼 

Just had the one question about whether we'll be sacrificing any performance by not sharing a long-lived connection in the codebase.

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs (hunk 1 above)
Comment (mitchellwrosen) [reply parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:537]: I do think it'd be wiser to reuse connections wherever possible - @tstat suggested we just use a connection pool. In the meantime, I'm not sure about where we might be hitting these functions in a tight loop - I did time loading the root branch of full-history `base` into memory, and there wasn't any noticeable slowdown. Push/pull to Share, at least, aren't using this `Codebase` interface for storing terms, so we don't have a blowup of connection creation/destruction over there.

Comment (ChrisPenner) [reply parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:537]: Yeah, I thought about a pool but wasn't sure whether it makes sense or not given how much lighter-weight sqlite connections are. Wouldn't hurt though, and probably would be easy to wire into what you've got here right?

If it's not showing any noticeable difference maybe it's fine?
