### PR TITLE
Fix implementation of getbuffering builtin to actually return Either

### LINKED ISSUE #2767: Mismatched implementation for `getBuffering.impl` builtin.
```unison
main : '{IO, Exception} ()
main _ = let
  bug (getBuffering.impl stdIn)
  ()
```

```ucm
.> run main

  💔💥

  I've encountered a call to builtin.bug with the following value:

    NoBuffering

  I'm sorry this message doesn't have more detail about the location of the failure.
  My makers plan to fix this in a future release. 😢
```

I'd expect it to report `Left NoBuffering` instead.

It appears the implementation of the builtin doesn't wrap its result in an Either like the helper in `base` requires.

I'm unfamiliar with how built-ins are implemented, Stew ran me through a bit of it and we have an attempt-in-progress [here](https://github.com/unisonweb/unison/compare/cp/fix-get-buffering) but ended up getting stuck.

Will likely need a hand from @dolio  when he's back from holidays.

Here's the section which most likely needs to change: https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/src/Unison/Runtime/Builtin.hs#L869-L886

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

Fixes builtin implementation for `getBuffering.impl`, previously it ran without crashing on trunk by fluke; but didn't behave correctly (it would treat the either's tag as the buffering type, so everything appeared to have `NoBuffering`)

closes #2767;

This should fix the failing `io` transcript on the `topic/rehash-codebase` branch.

## Implementation notes

Wrap the result in the appropriate either correctly inside the runtime.

## Test coverage

Added a line to the io transcript which actually checks the result of getBuffering.

### CODE REVIEW

File: parser-typechecker/src/Unison/Runtime/Builtin.hs [hunk 1]
```diff
@@ -866,24 +866,39 @@ set'buffering instr
...
-  TMatch bu . MatchSum  $ mapFromList
-  [ no'buf --> [] --> TCon Ty.bufferModeRef no'buf []
-  , line'buf --> [] --> TCon Ty.bufferModeRef line'buf []
-  , block'buf --> [] --> TCon Ty.bufferModeRef block'buf []
-  , sblock'buf --> [UN] -->
-        TAbs w
-      . TLetD n BX (TCon Ty.natRef 0 [w])
-      $ TCon Ty.bufferModeRef sblock'buf [n]
-  ]
+get'buffering'output :: forall v. Var v => v -> v -> v -> v -> v -> v -> ANormal v
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Runtime/Builtin.hs:869]: I worked with @dolio  to fix this;
we also attempted to abstract a helper for fmap'ing over an Either like this, but unfortunately it's not easy to do so.

**Review by aryairani — APPROVED** [review]
LGTM? But @dolio could you take a look too? Thanks.

**Review by dolio — APPROVED** [review]
Looks good to me, too.
