### PR TITLE
Fix Delta semigroup instance

### LINKED ISSUE #424: incorrect render width for watch expressions?
```
use Optional Some None
use Universal <

Sequence.foldl : (b -> a -> b) -> b -> [a] -> b
Sequence.foldl f b s =
  go i b = case Sequence.at i s of
    Some a -> go (i + 1) (f b a)
    None -> b
  go 0 b

> foldl (a -> b -> a Nat.+ b)

```

with a terminal width of 71 yielded:

image

whereas it seems like there should be a linebreak after `->` so that the line doesn't overflow?

It doesn't reflow until I reduce the terminal width to 58:

image

### PR DESCRIPTION
**Pull request by mitchellwrosen**
##  Overview

This patch amends `Pretty.Delta` to better model what it's meant to keep track of: the rectangular region that a `Pretty` fits in.

Previously, it kept track of

- Number of newlines
- Width of widest column
- Width of last column

But missing (crucially) was the width of the _first_ column. This is necessary for appending `Delta`s together: the first column of the right hand side is appended to the last column of the left hand side, and this new column may also now be the widest column.

Because this info was missing from `Delta` before, some things ended up overflowing (like #424) when they shouldn't have. This patch does fix #424, though due to an unrelated change in the term printer, the actual example given in that issue description no longer overflows. Still, I cherry-picked this work on top of `67a72c77263c0072cc0c99a190d73b6b9f23f0e9` (a random commit from around that time that exhibited the issue) and saw that it was fixed.

Another problem, also addressed: `Delta`'s `<>` implementation wasn't associative.

## Implementation notes

Before:

```haskell
-- lines, first col, max col
data Delta = Delta Int Int Int
```

Now:

```haskell
data Delta = 
    -- col
    SingleLine Int
    -- first col, last col, max col 
  | MultiLine Int Int Int
```

The switch to a sum type was just motivated by the observation that we don't care how many newlines a `Delta` contains, only whether it's `> 0`.

## Test coverage

The associativity of `Delta` is now under test.

### CODE REVIEW

File: parser-typechecker/src/Unison/TermPrinter.hs [hunk 1]
```diff
@@ -224,16 +223,15 @@ pretty0
...
       where optSpace = PP.orElse "" " "
     If' cond t f -> paren (p >= 2) $
-      if height > 0 then PP.lines [
+      if PP.isMultiLine pt || PP.isMultiLine pf then PP.lines [
         (fmt S.ControlKeyword "if ") <> pcond <> (fmt S.ControlKeyword " then") `PP.hang` pt,
         (fmt S.ControlKeyword "else") `PP.hang` pf
        ]
       else PP.spaced [
-        (fmt S.ControlKeyword "if") `PP.hang` pcond <> ((fmt S.ControlKeyword " then") `PP.hang` pt),
+        ((fmt S.ControlKeyword "if") `PP.hang` pcond) <> ((fmt S.ControlKeyword " then") `PP.hang` pt),
```
Comment (mitchellwrosen) [inline parser-typechecker/src/Unison/TermPrinter.hs:231]: Oops, I left this in while investigating the relationship between infix `PP.hang` and `<>`. Should I remove it?

File: parser-typechecker/src/Unison/Util/Pretty.hs [hunk 2]
```diff
@@ -132,7 +134,18 @@ instance Functor Pretty where
   fmap f (Pretty d o) = Pretty d (mapLit f $ fmap (fmap f) o)
 
 data F s r
-  = Empty | Group r | Lit s | Wrap (Seq r) | OrElse r r | Append (Seq r)
+  = Empty
+    -- | A group adds a level of breaking. Layout tries not to break a group
```
Comment (mitchellwrosen) [inline parser-typechecker/src/Unison/Util/Pretty.hs:138]: I copied a short explanation from Paul on Slack, hope that's ok.

File: parser-typechecker/src/Unison/TermPrinter.hs (hunk 1 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/TermPrinter.hs:231]: I'd keep it.

File: parser-typechecker/src/Unison/Util/Pretty.hs [hunk 3]
```diff
@@ -669,25 +710,49 @@ instance Monoid (Pretty s) where
...
 
 chDelta :: Char -> Delta
-chDelta '\n' = Delta 1 0 0
-chDelta _ = Delta 0 1 1
+chDelta '\n' = MultiLine 0 0 0
+chDelta _ = SingleLine 1
 
 preferredWidth :: Pretty s -> Width
-preferredWidth p = col (delta p)
+preferredWidth p = lastCol (delta p)
```
Comment (mitchellwrosen) [inline parser-typechecker/src/Unison/Util/Pretty.hs:749]: This might be a bug. I decided not to change the behavior, but it seems weird to say the "preferred width" of something is however wide its last column is.

Still, I'd like to at least have an idea of what changing this to `maxCol` or something might fix, so I left it as-is for now.

File: parser-typechecker/unison-parser-typechecker.cabal [hunk 4]
```diff
@@ -2,7 +2,7 @@ name:          unison-parser-typechecker
 category:      Compiler
 version:       0.1
 license:       MIT
-cabal-version: >= 1.8
+cabal-version: >= 1.10
```
Comment (mitchellwrosen) [inline parser-typechecker/unison-parser-typechecker.cabal:5]: This fixes a warning

File: parser-typechecker/unison-parser-typechecker.cabal [hunk 5]
```diff
@@ -223,6 +224,8 @@ library
     TypeApplications
     -- ViewPatterns
 
+  default-language: Haskell2010
```
Comment (mitchellwrosen) [inline parser-typechecker/unison-parser-typechecker.cabal:227]: These things fix warnings

File: parser-typechecker/src/Unison/Util/Pretty.hs (hunk 3 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/Util/Pretty.hs:749]: @pchiusano

File: parser-typechecker/unison-parser-typechecker.cabal (hunk 4 above)
Comment (aryairani) [reply parser-typechecker/unison-parser-typechecker.cabal:5]: Normally prefer to have this sort of thing in a separate PR, but no need to redo it.

**Comment by pchiusano** [comment]
Cool! Nice work.
