### PR TITLE
Fixes rogue names being displayed in Codebase server

### LINKED ISSUE #2360: Codebase server: the wrong docs seems to sometimes be shown
Here's an example from Unison Share where `Set.fromList` is showing the `Stream.fromList` docs.

It seems to happen for `Set.fromList` only if the UI perspective is `base.Set`.

Screen Shot 2021-08-29 at 11 16 47

This is a codebase-server issue only, doesn't happen in UCM.

### LINKED ISSUE #2531: READMEs from the /namespaces API doesn't seem to do name resolution correctly
When looking at a README thats fetched via the namespaces API, dependencies are often hashes. If that same definition was opened via the /getDefinition API the names are there.

### LINKED ISSUE #2557: Some wild doc selection when passing `relativeTo` parameter
I'm in perspective with `unison.base.Text`, and I'm viewing `Text.take` and `Text.drop`. It's showing me the docs for `MVar.take` (called `MVar.take.doc` presumably) and `Stream.drop` (called `Stream.drop.doc`). 

Screen Shot 2021-10-27 at 11 06 48 PM

What I think is happening is:

* The `Names` being used is one that includes all names, not just those in the current namespace.
* When looking at `take`, it's doing a suffixed lookup of `take.doc` to locate the docs, and it's finding `MVar.take.doc` outside the current namespace given by the `relativeTo`.

I think the fix is perhaps as simple as not doing a suffixed lookup when resolving docs - it's gotta be an exact match for the correct FQN.

If that doesn't work:

* Just use the local names at the specified `relativeTo` path for purposes of finding docs for a definition.
* The overall names should still be used for pretty-printing, since definitions may reference stuff outside the current namespace and we want those to get names, not hashes, in their rendering.

### PR DESCRIPTION
**Pull request by ChrisPenner**
Paired with @hojberg 😄 

## Overview

Makes desired name scoping explicit in backend name queries.

This allows the backend server to explicitly state that it wants names from ONLY the current qualified path, or whether it wants all names, but absolutely qualified.

closes #2557 
closes #2360 
closes #2531

## Implementation notes

Adds a sum-type to the path provided to name queries to require deciding whether names outside of that path should be included.

## Interesting/controversial decisions

Nah

## Test coverage

* We should probably have some tests for the codebase server handlers at some point.

### CODE REVIEW

**Comment by hojberg** [comment]
There's a strange side-effect of an empty list for type names showing up (which the UI doesn't expect). Debugging that a bit further.

**Review by pchiusano — APPROVED** [review]
Something to check:

If I've changed my perspective to `distributed` and view a definition that uses something from `base`, do I still see a proper name for it and not a hash?

For instance https://share.unison-lang.org/@bbipr4ode027l26cc9m5obsvo06dn5uaqogm5hc7bllgi5qjdrh9t024td24ihg1ioabpncv3i3nrpgqkcf103u0fnjbrnhpqk7c438/terms/unison/distributed/Remote/raceAt

There should be a call to [`List.any` in there](https://share.unison-lang.org/@bbipr4ode027l26cc9m5obsvo06dn5uaqogm5hc7bllgi5qjdrh9t024td24ihg1ioabpncv3i3nrpgqkcf103u0fnjbrnhpqk7c438/types/@o8dfai63ij3vi035ekgntappg20mim9qt8gatho216dr40g6bgmek5li3clbfsrsbd02lkq0kf3p9gti6ce0htdndp7a27ck9shqi80), which should render as `List.any` even if I'm within the distributed perspective.

(There's also currently a call to #a24n692uhl, which is `List.map_` which I just haven't pushed up to share or gotten into suitable shape for adding to base)

**Comment by hojberg** [comment]
@pchiusano yeah there's a bug with this that I just pushed a fix for.

There's also a bug with finding definitions by hash, which is used when clicking on links in the source. So like, clicking `List.any` in your example. In this branch, that doesn't find the term.

**Comment by hojberg** [comment]
I think there's a refactor that this part of the code could benefit from, to make it easier to have the right combination of names for lookup and names for display.

**Comment by hojberg** [comment]
Also, randomly, there seem to be a side-effect of this change on the renderWidth of signatures.

**Comment by hojberg** [comment]
I think I've fixed everything, but the refactor and render width issues (both of which we might do in a separate effort?).

cc @pchiusano @ChrisPenner

File: parser-typechecker/src/Unison/Server/Backend.hs [hunk 1]
```diff
@@ -647,25 +671,35 @@ prettyDefinitionsBySuffixes relativeTo root renderWidth suffixifyBindings rt cod
...
         rel = Names.terms $ currentNames parseNames
-        f k _ = Set.fromList . fmap Name.toText . filter isAbsolute . toList
+        f k _ = Set.fromList . fmap Name.toText . toList
               $ R.lookupRan (Referent.Ref k) rel
+
       typeFqns :: Map Reference (Set Text)
       typeFqns = Map.mapWithKey f types
        where
         rel = Names.types $ currentNames parseNames
-        f k _ = Set.fromList . fmap Name.toText . filter isAbsolute . toList
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Backend.hs:667]: Absolute filtering caused the `typeNames` field to be blank. The UI (currently) expects at least 1 name. In most cases that name would be the same as the "bestName".

File: parser-typechecker/src/Unison/Server/Backend.hs [hunk 2]
```diff
@@ -647,25 +671,35 @@ prettyDefinitionsBySuffixes relativeTo root renderWidth suffixifyBindings rt cod
     -- the names in the pretty-printer, but the current implementation
     -- doesn't.
     let
+      -- We use printNames for names in source and parseNames to lookup
+      -- definitions, thus printNames use the allNames scope, to ensure
+      -- external references aren't hashes.
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Backend.hs:676]: I think it's worth doing a refactor around this to ensure that all codebase server endpoints does the right thing for printNames vs parseNames.

File: parser-typechecker/src/Unison/Server/Endpoints/FuzzyFind.hs [hunk 3]
```diff
@@ -150,11 +149,12 @@ serveFuzzyFind h codebase mayRoot relativePath limit typeWidth query =
       let b0 = Branch.head branch
           alignments =
             take (fromMaybe 10 limit) $ Backend.fuzzyFind rel branch (fromMaybe "" query)
-          ppe = Backend.basicSuffixifiedNames hashLength branch rel
+          -- Use AllNames to render source
+          ppe = Backend.basicSuffixifiedNames hashLength branch (Backend.AllNames rel)
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Endpoints/FuzzyFind.hs:153]: when there's a PPE involved, the names are used for rendering source.

File: parser-typechecker/src/Unison/Server/Endpoints/GetDefinitions.hs [hunk 4]
```diff
@@ -119,21 +119,26 @@ serveDefinitions
...
     h
     rel <-
       fmap Path.fromPath' <$> traverse (parsePath . Text.unpack) relativePath
     ea <- liftIO . runExceptT $ do
       root <- traverse (Backend.expandShortBranchHash codebase) mayRoot
-      Backend.prettyDefinitionsBySuffixes rel
+      let hqns = HQ.unsafeFromText <$> rawHqns
+          scope = case hqns of
+            -- TODO: Change this API to support being queried by just 1 name/hash
+            HQ.HashOnly _ : _ -> Backend.AllNames . fromMaybe Path.empty $ rel
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Endpoints/GetDefinitions.hs:132]: We want disregard the confined relativeTo scope for definitions queried by hash.

File: parser-typechecker/src/Unison/Server/Endpoints/NamespaceListing.hs [hunk 5]
```diff
@@ -217,7 +217,7 @@ serve tryAuth codebase mayRoot mayRelativeTo mayNamespaceName =
       let listingBranch = Branch.getAt' path root
       hashLength <- liftIO $ Codebase.hashLength codebase
 
-      let shallowPPE = Backend.basicSuffixifiedNames hashLength root $ Path.fromPath' path'
+      let shallowPPE = Backend.basicSuffixifiedNames hashLength root $ (Backend.Within $ Path.fromPath' path')
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Endpoints/NamespaceListing.hs:220]: Using `Backend.Within` here feels a little redundant. It's a Shallow query, so its not like we'll get names from outside the path.

File: parser-typechecker/src/Unison/Server/Backend.hs [hunk 6]
```diff
@@ -442,12 +452,27 @@ termReferentsByShortHash codebase sh = do
 -- currentPathNames :: Path -> Names
 -- currentPathNames = Branch.toNames . Branch.head . Branch.getAt
 
-getCurrentPrettyNames :: Path -> Branch m -> NamesWithHistory
-getCurrentPrettyNames path root =
-  NamesWithHistory (basicPrettyPrintNames root path) mempty
+-- | Configure how names will be constructed and filtered.
+--   this is typically used when fetching names for printing source code or when finding
+--   definitions by name.
+data NameScoping =
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Backend.hs:458]: It's now an explicit choice by the consumer which scoping behavior they'd like.

**Comment by hojberg** [comment]
Also added a names fix for https://github.com/unisonweb/unison/issues/2531

File: parser-typechecker/src/Unison/Server/Backend.hs [hunk 7]
```diff
@@ -261,13 +272,12 @@ findShallowReadmeInBranchAndRender ::
   Width ->
   Rt.Runtime v ->
   Codebase IO v Ann ->
+  NamesWithHistory ->
```
Comment (hojberg) [inline parser-typechecker/src/Unison/Server/Backend.hs:275]: This takes names for printing instead of looking it up. It never needs names for term lookup, and the print names for the README need to be for the root branch to avoid hashes in rendered source.

Comment (hojberg) [reply parser-typechecker/src/Unison/Server/Backend.hs:275]: Perhaps we should use this pattern of creating names on the consumer side everywhere?
