### PR TITLE
fix and demonstrate find-by-type in v2 codebase

### LINKED ISSUE #2140: something fishy with find by type / type-mention
`find : Nonempty a -> a` doesn't seem to find `Nonempty.last` (or anything else).
`Nonempty.last` is `#4s2e6fpcpb`

In my v1 codebase, I see these hashes in the type-mentions-index for `Nonempty.last`:
`% find ~/.unison/v1/type-mentions-index/ | grep 4s2e6fpcpb`
```
#gku1kqleg9n619vfvu1iuig4fe3f937o3nbaa0dq0man4tjhg07idfadst0e5pufnnbh5ckun4rhl0f3ob2fnodimgm4sel20oau2qo
#9f58iojnfqnkf14ifh966q052vv9u8f3ov58icl53qre0jtn2m05fdfhasnjllvv7qv599ctbt188uc2b7d8bp4em1ds4t9lhvnkuso
#kh9ar9iiaa3sn503l5rqmo7josbjvpe9qfh2nn5qpqdtg0df9un3bn59dkhdfkhphcddril2b0d4g4gjs8eqipejrmco16dj4ta2vog
#mlcfeh2294igm228dlq3u9bn0i0c42q8fc700f6c57tpqntn7omoml9liepcvkq3v9v79n824d9t0rp63otl6f86purvlv08gu56ih0
#94a25njontg9htj2q8elv0jajublc92q5c6t3mrj0p17if0j5lfc6nnp7jgr4km0vjm0v2rucb63dvjnpeltj53jhs4m63mpnqp42mo
```

In my v2 codebase I see these hashes in the type-mentions-index for `Nonempty.last`:
```sql
select out.base32 
from find_type_mentions_index, hash_object, hash, hash as out 
where hash.base32 like '4s2e6fpcpb%' 
  and hash.id = hash_id 
  and object_id=term_referent_object_id 
  and type_reference_hash_id = out.id;
```

```
4ej7f14gj2761smju0pdk9b1v1aflunmjtej8ek562rrd9dlkvr9ak2q0p28tf2m37003jq9a2sffdavpgcv9uiinncdruf7qps2l3g
6hvd1hivr57ok2ftti8carcai9eag2dunrb3r5k84nef2e6vcjjosnqdsogqfjhebh8hbc7tsmq4jc2gmi0bl1q0ke06cud2e8utkbo
9f58iojnfqnkf14ifh966q052vv9u8f3ov58icl53qre0jtn2m05fdfhasnjllvv7qv599ctbt188uc2b7d8bp4em1ds4t9lhvnkuso
gku1kqleg9n619vfvu1iuig4fe3f937o3nbaa0dq0man4tjhg07idfadst0e5pufnnbh5ckun4rhl0f3ob2fnodimgm4sel20oau2qo
skpghar6nnkqrsl76gb0qq8jn1a2kfnbpf2ts7jffopc9ar2jrj5t10s4cbd0kk53bu8mr2dughhinr8gluqi31kn94912ie9rjlq60
```

2 of the 5 match, so my guess is that the hashes are being computed wrong for the index although it was meant to be computed in the same way as before.

After figuring out what's wrong with computing the hashes, we'll need either a command to rebuild the two indexes, or (probably better for users) increment the schema version number and rebuild the indexes automatically on the first startup.

Also we should improve our test coverage since this isn't being flagged.

### PR DESCRIPTION
**Pull request by aryairani**
This PR pulls a conflicting hashing implementation out of the v2 codebase, and delegates to the newly modularized ones from #2433 via `SqliteCodebase.hs`.

It also fixes an incidental bug in `HandleInput.hs` (necessary to create the working [demo transcript](https://github.com/unisonweb/unison/blob/37115f790e44b9ab2d6aeb49fe77deefb6ac91f1/unison-src/transcripts/find-by-type.output.md)) which caused `find :` to fail to fall back to fuzzy matching if the only known exact-matches were unnamed. 

Fixes #2140 (though only for new terms, not terms created with older builds of ucm), but not #2332.

### CODE REVIEW

**Review by pchiusano — APPROVED** [review]
Great!

**Comment by aryairani** [comment]
@mitchellwrosen This PR also deletes `U.Util.Hashable` like we discussed.

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 1]
```diff
@@ -419,14 +421,33 @@ sqliteCodebase debugName root = do
...
+          addTermComponentTypeIndex oId types = for_ (types `zip` [0..]) \(tp, i) -> do
+            let self = C.Referent.RefId (C.Reference.Id oId i)
+                typeForIndexing = Hashing.typeToReference tp
+                typeMentionsForIndexing = Hashing.typeToReferenceMentions tp
+            Ops.addTypeToIndexForTerm self (Cv.reference1to2 typeForIndexing)
+            Ops.addTypeMentionsToIndexForTerm self (Set.map Cv.reference1to2 typeMentionsForIndexing)
+
+          addDeclComponentTypeIndex :: EDB m => ObjectId -> [[Type Symbol Ann]] -> m ()
+          addDeclComponentTypeIndex oId ctorss =
+            for_ (ctorss `zip` [0..]) \(ctors, i) ->
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:434]: Just a heads up that there's an `ifor_` in [`Data-Foldable-WithIndex` ](https://hackage.haskell.org/package/indexed-traversable-0.1.1/docs/Data-Foldable-WithIndex.html)

Which we already depend on since it's used by `lens`.

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 2]
```diff
@@ -419,14 +421,33 @@ sqliteCodebase debugName root = do
...
           tryFlushTermBuffer h =
             tryFlushBuffer
               termBuffer
-              ( \h2 ->
-                  void . Ops.saveTermComponent h2
-                    . fmap (first (Cv.term1to2 h) . second Cv.ttype1to2)
+              ( \h2 component -> do
+                  oId <- Ops.saveTermComponent h2
+                    $ fmap (bimap (Cv.term1to2 h) Cv.ttype1to2) component
+                  addTermComponentTypeIndex oId (fmap snd component)
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:450]: Is there ever a case where we DON'T want to add a type index after saving a term?
Just curious what's the best way to avoid accidentally forgetting to do this.

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs (hunk 1 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:434]: TIL

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs (hunk 2 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:450]: No, we always want to; we just have to do it in a place where it's easy to ensure that the hashing function and representation used for building the index is the same as the one used for querying the index.

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs (hunk 1 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:434]: Hm, though it looks like there's an `instance Lens.FoldableWithIndex Int []` and not for other `Integral` index types, which we use all over. (Why would we want to allow negative indexes?)
