### PR TITLE
Fix #947

### LINKED ISSUE #947: Subtype check problem in typechecker
This program should not typecheck, because `forall e . Nat ->{Log,e} Nat` is not a subtype of `forall e . Nat ->{e} Nat`:

```
ability Log where
  log : Text -> ()

foo : (∀ e . Nat ->{e} ()) -> Nat
foo _ = 0

bar : (∀ e . Nat ->{e,Log} ()) -> Nat
bar f = foo f
```

But it does typecheck currently, which is wrong!

### PR DESCRIPTION
**Pull request by pchiusano**
This was an amazing bug. Given an ability check for `{e, Other}`, and ambient of `{e2}`, we were bailing with a successful ability check after just the first `e` request, but not even checking the `Other` request against ambient. `e` had to be an unsolved existential to trigger this.

See the note below.

### CODE REVIEW

File: parser-typechecker/src/Unison/Typechecker/Context.hs [hunk 1]
```diff
@@ -1555,12 +1555,13 @@ abilityCheck' ambient0 requested0 = go ambient0 requested0 where
...
+        Type.Existential' b v -> do
           let et2 = Type.effects (loc r) ambient
           -- instantiate it to `{}` if can't cover all of ambient
-          in instantiateR et2 b v `orElse`
-             instantiateR (Type.effects (loc r) []) b v `orElse`
-             die1
+          instantiateR et2 b v 
+            `orElse` instantiateR (Type.effects (loc r) []) b v 
+            `orElse` die1
+          go ambient rs
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/Typechecker/Context.hs]: This recursive call `go ambient rs` was straight up missing. `rs` is the remainder of the requested abilities.
