### PR TITLE
Fix roundtrip error with block lambdas

### LINKED ISSUE #3110: Roundtrip error for multi-line lambda syntax
The following code, with a multi-line lambda, can be added to the codebase: 

```
tmp =
  List.map (
    i -> let
      use Nat +
      x = i + 1
      y = x + 1
      z = y + 1
      z
  ) [1, 2, 3]

```

Upon saving and editing, the following, non-typechecking code is rendered back: 

```
tmp : [Nat]
tmp =
  use Nat +
  List.map
    (i ->
      x = i + 1
      y = x + 1
      z = y + 1
      z) [1, 2, 3]
```

In order to allow the expression to typecheck, folks are adding newlines or `let` expressions. 

Another example from the slack: 

```
-- this fails 
sum2 : List Nat -> Nat
sum2 = fromList >> mcata
  (f -> cases
    NilF -> 0 
    ConsF x xs -> x + (f xs))

-- but this typechecks
sum : List Nat -> Nat
sum = 
  fromList >> mcata
    (f -> cases
      NilF -> 0
      ConsF x xs -> x + (f xs))
```

### PR DESCRIPTION
**Pull request by runarorama**
This is an attempt to fix #3110 and #3801 by always forcing a `let` (or `do`) if the body of a lambda is a multi-line block.

There might be a better way of addressing this, but I suspect there's a parser issue that prevents a block being detected after the opening `->` of the lambda body. If always adding the `let` for a block lambda body is controversial, then I can look into that instead.

See transcript output diff for difference in output.

### CODE REVIEW

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs [hunk 1]
```diff
@@ -86,12 +86,12 @@ data AmbientContext = AmbientContext
...
-    infixContext :: InfixContext,
-    imports :: Imports,
-    docContext :: DocLiteralContext,
-    elideUnit :: Bool -- `True` if a `()` at the end of a block should be elided
+    precedence :: !Int,
+    blockContext :: !BlockContext,
+    infixContext :: !InfixContext,
+    imports :: !Imports,
+    docContext :: !DocLiteralContext,
+    elideUnit :: !Bool -- `True` if a `()` at the end of a block should be elided
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Syntax/TermPrinter.hs:96]: I took the opportunity to make this data structure strict, since it will always be used in a strict way anyway.

File: unison-src/transcripts-round-trip/main.output.md [hunk 2]
```diff
@@ -875,7 +875,7 @@ broken tvar =
           (cases
             Some _ ->
               "oh boy isn't this a very very very very very very very long string?"
-            None   -> ""))
+            None -> ""))
```
Comment (runarorama) [inline unison-src/transcripts-round-trip/main.output.md]: Changes in this file are unrelated. This transcript just hasn't been run for a while.

File: unison-src/transcripts/fix3265.output.md [hunk 3]
```diff
@@ -33,19 +33,20 @@ are three cases that need to be 'fixed up.'
...
+                  match y with
+                    0 -> w + x
+                    n -> 1 + f0 (drop y 1)
+                f0 y =
+                  match y with
+                    0 -> x
+                    n -> 1 + f1 (drop y 1)
+                f2 x = f2 x
+                f3 x y = 1 + y + f2 x
+                g h = h 1 + x
```
Comment (runarorama) [inline unison-src/transcripts/fix3265.output.md:48]: This is the difference in output. Note the introduction of `let` at the start of the block.

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs [hunk 4]
```diff
@@ -484,16 +484,20 @@ pretty0
...
                     pbs <- printCase im doc branches
                     pure . paren (p >= 3) $
                       PP.group (fmt S.ControlKeyword "cases") `PP.hang` pbs
                   LamsNamedPred' vs body -> do
-                    prettyBody <- pretty0 (ac 2 Block im doc) body
+                    prettyBody <- pretty0 (ac 2 Normal im doc) body
+                    let hang = case body of
+                          Delay' (Lets' _ _) -> PP.softHang
+                          Lets' _ _ -> PP.softHang
+                          _ -> PP.hang
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Syntax/TermPrinter.hs:517]: This allows the `let` keyword to appear on the same line as the arrow.

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs [hunk 5]
```diff
@@ -484,16 +484,20 @@ pretty0
...
                     pure $ f' `PP.hang` args'
-                _ -> case (term, \v -> nonUnitArgPred v && not (isDelay term)) of
+                _other -> case (term, \v -> nonUnitArgPred v && not (isDelay term)) of
                   (LamsNamedMatch' [] branches, _) -> do
                     pbs <- printCase im doc branches
                     pure . paren (p >= 3) $
                       PP.group (fmt S.ControlKeyword "cases") `PP.hang` pbs
                   LamsNamedPred' vs body -> do
-                    prettyBody <- pretty0 (ac 2 Block im doc) body
+                    prettyBody <- pretty0 (ac 2 Normal im doc) body
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Syntax/TermPrinter.hs:513]: Changing `Block` to `Normal` forces the `let` to show up in the body of a lambda.

**Review by ChrisPenner — APPROVED** [review]
Seems good 👍🏼 

It may be worth thinking through the ideal situation we want here though;
I think as an end user I'm likely to get confused about when I need a `let` vs not, so maybe it'd be best long-term if the pretty printer either ALWAYS used a let, or NEVER used a let (and the parser could handle it) 😄
