### PR TITLE
make io.test look in scratch file first

### LINKED ISSUE #3654: `io.test` claims to look for test in the scratch file but does not
This one is quite annoying because you generally want to get tests passing before adding definitions to the codebase. 

```
  ...
  SemispaceCache.tests.ex1           : '{IO, Exception} [test.Result]

.distributed.main> io.test SemispaceCache.tests.ex1

  😶
  
  I looked for a function `SemispaceCache.tests.ex1` in the most recently typechecked file and
  codebase but couldn't find one. It has to have the type:
  
    SemispaceCache.tests.ex1 : '{IO, Exception} [test.Result]

.distributed.main>                                         
```

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

Fixes #3654 

This PR makes `io.test <name>` look in the scratch file for `<name>` (as it claimed it did).

Along the way, I also improved the error message for when `io.test <name>` resolves to multiple terms with name `<name>`. Previously, it just output the same "no main" error message you'd get when `<name>` doesn't refer to anything. Now, you'll get a "`<name>` is ambiguous" error.

### CODE REVIEW

File: unison-cli/src/Unison/Codebase/Editor/HandleInput.hs [hunk 1]
```diff
@@ -1869,6 +1835,83 @@ handleDiffNamespaceToPatch description input = do
...
+        ]
+
+  matches <-
+    Cli.label \returnMatches -> do
+      -- First, look at the terms in the latest typechecked file for a name-match.
+      whenJustM Cli.getLatestTypecheckedFile \typecheckedFile -> do
+        let refToType :: Reference -> Type Symbol Ann
+            refToType ref =
+              typecheckedFile
+                & UF.indexByReference
```
Comment (ChrisPenner) [inline unison-cli/src/Unison/Codebase/Editor/HandleInput.hs]: I think this might be doing more work than necessary here; at a glance it looks like we can use `UF.hashTermsId`, or is there maybe a benefit I'm missing?

File: unison-cli/src/Unison/Codebase/Editor/HandleInput.hs [hunk 2]
```diff
@@ -1869,6 +1835,83 @@ handleDiffNamespaceToPatch description input = do
...
+        when (not (null matches)) (returnMatches matches)
+
+      -- Then, if we get here (because nothing in the scratch file matched), look at the terms in the codebase.
+      fmap catMaybes do
+        Cli.runTransaction do
+          for (Set.toList (NamesWithHistory.lookupHQTerm main parseNames)) \ref0 ->
+            runMaybeT do
+              ref <- MaybeT (pure (Referent.toTermReference ref0))
+              typ <- MaybeT (loadTypeOfTerm codebase (Referent.Ref ref))
+              pure (ref, typ)
```
Comment (ChrisPenner) [inline unison-cli/src/Unison/Codebase/Editor/HandleInput.hs]: Nit;

```suggestion
      Cli.runTransaction do
        forMaybe (Set.toList (NamesWithHistory.lookupHQTerm main parseNames)) \ref0 ->
          runMaybeT do
            ref <- MaybeT (pure (Referent.toTermReference ref0))
            typ <- MaybeT (loadTypeOfTerm codebase (Referent.Ref ref))
            pure (ref, typ)
```

**Review by ChrisPenner — APPROVED** [review]

File: unison-cli/src/Unison/Codebase/Editor/HandleInput.hs (hunk 1 above)
Comment (mitchellwrosen) [reply unison-cli/src/Unison/Codebase/Editor/HandleInput.hs]: Yeah, I think that would be better. I was trying to leverage existing stuff (converting a unison file to a `Names`, inverting the `hashTermsId` to lookup by reference instead of name), but I agree it's meh as-written.

File: unison-cli/src/Unison/Codebase/Editor/HandleInput.hs (hunk 2 above)
Comment (mitchellwrosen) [reply unison-cli/src/Unison/Codebase/Editor/HandleInput.hs]: :+1: I didn't know about `Witherable.forMaybe`
