### PR TITLE
Fix misspelling / typo in help docs

### LINKED ISSUE #1203: pr.create command lists useless numbers
```
  The changes summarized below are available for you to review, using the following command:
  
    `pr.load https://github.com/unisonweb/base https://github.com/puffnfresh/base`
  
  Added definitions:
  
    1. Either.swap      : Either a b -> Either b a
    2. Tuple.swap       : Tuple a b -> Tuple b a
    3. Weighted.eithers : Weighted a -> Weighted b -> Weighted (Either a b)
    4. Weighted.tuples  : Weighted a -> Weighted b -> Weighted (Tuple a b)
```

The numbers here refer to an in-memory branch which is gone by the time they are printed, so you'll get errors if you try to interact with them.
```
.> view 1

  ⚠️
  
  The following names were not found in the codebase. Check your spelling.
    .Either.swap#8hr15i0otmkr4npjlva0c06lgvif4qagktr9tl4cls6och8uellgtoef614rivqj9d3s27ajilc6i0b2fpu4j3ol2n4hutc0ok1727g
```

Suggest passing a flag to the output to suppress the numbering?

### PR DESCRIPTION
**Pull request by virusdave**
See title.
Fixes a misspelling / typo in the `help` docs.

### CODE REVIEW

File: parser-typechecker/src/Unison/CommandLine/InputPatterns.hs [hunk 1]
```diff
@@ -1169,7 +1169,7 @@ unlink = InputPattern
   ["delete.link"]
   [(Required, definitionQueryArg), (OnePlus, definitionQueryArg)]
   (fromString $ concat
-    [ "`unlink metadata defn` removes a link to `detadata` from `defn`."
+    [ "`unlink metadata defn` removes a link to `metadata` from `defn`."
```
Comment (aryairani) [inline parser-typechecker/src/Unison/CommandLine/InputPatterns.hs:1172]: lol
