### PR TITLE
Use socket operations for LSP client communication to avoid errors on socket close

### LINKED ISSUE #3732: LSP: resource vanished when scratch file is closed
When I am working in a Scratch file with LSP enabled (in Vim, but I imagine that this would happen for other editors as well), and then I close that Scratch file, I often get the following in my UCM window:

```
.myproject.main> <socket: 76 >: hPutBuf: resource vanished ( Broken pipe )
```

As far as I can tell there aren't any other issues; just the error message.

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

Just a quick one;

fixes #3732 

## Implementation notes

Use socket send/receive operations instead of Handle operations;
The socket operations know whether the socket is still active and don't seem to error when it's closed.

## Testing

I tried it out a few times locally, I get the error on trunk, not on this branch.

### CODE REVIEW

File: unison-cli/src/Unison/LSP.hs [hunk 1]
```diff
@@ -58,12 +58,18 @@ spawnLsp codebase runtime latestBranch latestPath =
     UnliftIO.handleIO (handleFailure lspPort) $ do
       TCP.serve (TCP.Host "127.0.0.1") lspPort $ \(sock, _sockaddr) -> do
         Ki.scoped \scope -> do
-          sockHandle <- socketToHandle sock ReadWriteMode
+          let clientInput = do
+                -- The server will be in the process of shutting down if the socket is closed,
+                -- so just return empty input in the meantime.
+                fromMaybe "" <$> TCP.recv sock defaultChunkSize
```
Comment (ChrisPenner) [inline unison-cli/src/Unison/LSP.hs:67]: In theory this could lead to an infinite loop of trying to get more data from the client because it never returns any new bytes, but in reality `TCP.serve` will always shut down this thread when the socket closes so that'll never come up. If anyone has a better solution let me know, but otherwise this should be fine 😄

**Review by pchiusano — APPROVED** [review]
😎

**Comment by ceedubs** [comment]
Thanks, @ChrisPenner!

Hmm I did a local `stack build && stack install unison-cli` and I'm seeing the following error:

```
.me> writev: resource vanished ( Broken pipe )
```

This is slightly different than the previous error:

```
.myproject.main> <socket: 76 >: hPutBuf: resource vanished ( Broken pipe )
```

Again, things still seem to work fine, but I do get the message on my screen.

**Comment by ChrisPenner** [comment]
Hrmm, strange that I'm not seeing those; I'll run another pass over it.

**Comment by ceedubs** [comment]
It could potentially be something bizarre with my dev environment setup 🤷

**Comment by ceedubs** [comment]
If this is an improvement in other ways I think that it would be fine to merge this but maybe keep the other issue open.

**Comment by ChrisPenner** [comment]
It seems to trigger more consistently if the language server is in the middle of serving a request when the editor closes, which makes sense of course.

@ceedubs  Pretty sure I've squashed it now, I brought out the big guns haha.

**Review by ceedubs — APPROVED** [review]
👍 no error messages now. Thanks, @ChrisPenner!
