### PR TITLE
Fixes #3523

### LINKED ISSUE #3523: `patch` fails with SQL error if the patch contains entries for hashes not in the user's codebase
Steps to reproduce:

1. Create a fresh codebase
2. `pull unison.public.base.releases.M4 base1`
3. `pull unison.public.base.releases.M4c base2`
4. `patch base2.patch base1`

```
Encountered exception:
SqliteQueryException
    { sql = "SELECT object.id
            FROM object
            JOIN hash ON object.primary_hash_id = hash.id
            WHERE hash.base32 = ? COLLATE NOCASE"
    , params = ""3e3rc9d77fh8mnjgtn5cvck814p5hc1u9vrkqq5bmkp7v61q2rg2hrloob5kai0hoh990pqt1p7k83vb3f1tcp24lim09f3fn1ttud0""
    , exception = ExpectedExactlyOneRowException
        { rows = "[]" }
    , callStack = []
    , connection = Connection
        { name = "main"
        , file = "/home/janet/.unison/v2/unison.sqlite3"
        }
    , threadId = ThreadId 20435
    }
```

The cause is that the hash `3e3rc9d77fh8mnjgtn5cvck814p5hc1u9vrkqq5bmkp7v61q2rg2hrloob5kai0hoh990pqt1p7k83vb3f1tcp24lim09f3fn1ttud0` doesn't exist in this codebase. It exists somewhere in the history of `base.main`.

The correct behaviour should be that the `patch` command ignores any "from" entries it doesn't have. And maybe gives a warning if it has the "from" hash but not the "to" hash in a patch entry.

`delete.term-replacement #3e3rc9d77fh8m` fails with `The following names were not found in the codebase. Check your spelling.`, so we can't even remove these entries from the patch.

### PR DESCRIPTION
**Pull request by tstat**
Don't require references in the patch's domain to exist in the codebase.

### CODE REVIEW

**Review by mitchellwrosen — APPROVED** [review]

File: unison-cli/src/Unison/Codebase/Editor/Propagate.hs [hunk 1]
```diff
@@ -265,10 +268,21 @@ propagate patch b = case validatePatch patch of
...
+                C.ReferenceDerived id_ ->
+                  Operations.objectExistsForHash (view C.idH id_) <&> \case
+                    True -> Just ref
+                    False -> Nothing
+              case mref of
+                Nothing -> pure mempty
+                Just ref -> Codebase.dependents codebase Queries.ExcludeOwnComponent ref
+          )
+          patch
+          (Names.contains names0)
```
Comment (aryairani) [inline unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: It looks like this is the crux of the fix; but is this where it should go?  I think I convinced myself that the problem is more here than in [`computeDirty`](https://github.com/unisonweb/unison/blob/travis/3523/unison-cli/src/Unison/Codebase/Editor/Propagate.hs#L705-L726), but maybe it really belongs in [`Codebase.dependents`](https://github.com/unisonweb/unison/blob/travis/3523/codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs#L1035-L1040) instead; wdyt?

**Review by aryairani — COMMENTED** [review]
Thanks for tracking this down! I left a question.

File: unison-cli/src/Unison/Codebase/Editor/Propagate.hs (hunk 1 above)
Comment (mitchellwrosen) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: We thought that it wouldn't be better to just relax a precondition on Codebase.dependents (that the given Reference must exist) without auditing the call sites. But maybe there aren't that many?

Comment (ChrisPenner) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: Semantically I think it makes sense that if we don't have a Reference in the codebase then the dependents of that reference must just be the empty set, are there any cases where you wouldn't expect that to be the case?

If this does affect other calls I suspect it just affects them by avoiding this same bug in other spots,  so maybe it's worth a quick audit? 🤔

Comment (mitchellwrosen) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: I don't think so - the caller might expect a reference to be there, and we'd be hiding a bug by returning the empty set of dependents. I think there are simply two versions of this function with different semantics.

Comment (aryairani) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: It would be okay to audit the call sites; I don't know how many there are, but it doesn't seem obviously necessary either. (I imagine they would all be in the context of "how much work do we have to do about this reference" and if the reference is unknown, then there's no work to do.)

It would also be okay to just return the empty set when the query is an unknown reference.  The contract of `Codebase.dependents` is to return whatever dependents are present in this codebase. So if the object itself isn't in the codebase, there would also necessarily be zero dependents present. (There will always be some dependents missing from the result; the ones that don't exist in this codebase.)

`Codebase.dependencies` (if it existed, which it doesn't currently) would be a different story. It should always return the complete set of dependencies for any known object, and its return type would reflect that.

WDYT @mitchellwrosen

Comment (mitchellwrosen) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: Ah, ok. If we say the contract of Codebase.dependents is that it does not require the input reference to exist in the codebase. then of course it's the right place for the change. There weren't any docs on Codebase.dependents so we proceeded conservatively.

Comment (aryairani) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: I guess we have flexibility here, but the contract probably shouldn't be that it crashes.

Comment (aryairani) [reply unison-cli/src/Unison/Codebase/Editor/Propagate.hs]: Let's go ahead and move it and maybe it will fix other things too :) /cc @tstat

**Review by ChrisPenner — APPROVED** [review]

**Comment by tstat** [comment]
I tested by following Runar's reproduction instructions, but with m3 and m4 rather than m4 and m4c.
