### PR TITLE
Fix universal quantifiers disappearing in nested bindings

### LINKED ISSUE #3055: pretty-printer drops forall when it shouldn't
Write the following function:

```
foo : 'a -> a
foo thunk =
  nested : forall a. a -> a
  nested x = x
  nested "hi"
  !thunk
```

This compiles just fine. However if you `add` it and then `edit` it, the pretty-printer rewrites it to

```
foo : '{g} a ->{g} a
foo thunk =
  nested : a -> a
  nested x = x
  nested "hi"
  !thunk
```

The universal quantification is stripped from `nested`, so it fails with the following error:

```
  The 1st argument to `nested`
  
            has type:  Text
      but I expected:  a
  
      3 |   nested : a -> a
      4 |   nested x = x
      5 |   nested "hi"
```

An alternative to preserving the universal quantification would be to alpha-normalize the type variable name, in which case this is related to #525 and #2699.

### PR DESCRIPTION
**Pull request by runarorama**
This refactors the pretty-printer to track the names of type variables. Also makes it monadic to make such modifications easier later.

Fixes https://github.com/unisonweb/unison/issues/3055

See my comments in self-review.

### CODE REVIEW

File: codebase2/util/src/U/Util/Monoid.hs [hunk 1]
```diff
@@ -10,6 +11,9 @@ intercalateMap :: (Foldable t, Monoid a) => a -> (b -> a) -> t b -> a
 intercalateMap separator renderer elements =
   mconcat $ intersperse separator (renderer <$> toList elements)
 
+intercalateMapM :: (Traversable t, Monad m, Monoid a) => a -> (b -> m a) -> t b -> m a
+intercalateMapM separator renderer = traverse renderer >=> return . intercalateMap separator id
+
```
Comment (runarorama) [inline codebase2/util/src/U/Util/Monoid.hs:16]: Added this monadic version of `intercalateMap`

File: lib/unison-pretty-printer/src/Unison/Util/Pretty.hs [hunk 2]
```diff
@@ -406,6 +407,9 @@ spaced = intercalateMap softbreak id
 spacedMap :: (Foldable f, IsString s) => (a -> Pretty s) -> f a -> Pretty s
 spacedMap f as = spaced . fmap f $ toList as
 
+spacedTraverse :: (Traversable f, IsString s, Applicative m) => (a -> m (Pretty s)) -> f a -> m (Pretty s)
+spacedTraverse f as = spaced <$> traverse f as
+
```
Comment (runarorama) [inline lib/unison-pretty-printer/src/Unison/Util/Pretty.hs:412]: Monadic version of `spacedMap`

File: parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+module Unison.PrettyPrintEnv.MonadPretty where
+
+import Control.Lens (over, set, view, views, _1, _2)
+import Control.Monad.Reader (MonadReader, Reader, local, runReader)
+import qualified Data.Set as Set
+import Unison.Prelude (Set)
+import Unison.PrettyPrintEnv (PrettyPrintEnv)
+import Unison.Var (Var)
+
+type MonadPretty v m = (Var v, MonadReader (PrettyPrintEnv, Set v) m)
```
Comment (runarorama) [inline parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs:12]: I decided to make this a constraint type alias rather than its own type class so I wouldn't have to write a bunch of instances.

File: parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+-- | Add type variables to the set of variables that need to be avoided
+addTypeVars :: MonadPretty v m => [v] -> m a -> m a
+addTypeVars = modifyTypeVars . Set.union . Set.fromList
+
+-- | Check if a list of type variables contains any variables that need to be
+-- avoided
+willCapture :: MonadPretty v m => [v] -> m Bool
+willCapture vs = views _2 (not . Set.null . Set.intersection (Set.fromList vs))
+
+runPretty :: Var v => PrettyPrintEnv -> Reader (PrettyPrintEnv, Set v) a -> a
```
Comment (runarorama) [inline parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs:46]: This instantiates the `MonadPretty` class to a simple `Reader`.

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs [hunk 5]
```diff
@@ -159,14 +162,12 @@ data DocLiteralContext
 -}
 
 pretty0 ::
-  forall v.
-  Var v =>
-  PrettyPrintEnv ->
+  forall v m.
+  MonadPretty v m =>
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Syntax/TermPrinter.hs:166]: The pretty-printer now uses a monad `m` which is constrained to be a `MonadReader` of the environment, including `PrettyPrintEnv` and the set of bound type variable names.

I decided to make this a constraint rather than a concrete class to make this easier to work with in the future, where the context may be something like `ReaderT PPEnv IO` or something. Avoids lifting and hoisting nonsense down the line.

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs [hunk 6]
```diff
@@ -734,69 +778,80 @@ a + b = ...
...
+          -- we want to print the type signature on the previous line.
+          -- The TypePrinter.pretty0 function prints the type, and uses a
+          -- Reader monad with (Set v) in it to track which type variables are
+          -- bound in the outer scope. We use that to determine if the type
+          -- printer should avoid capture of those variables.
+          let avoidCapture = case tp of
+                ForallsNamed' vs _ -> addTypeVars vs
+                _ -> id
+          tp' <- TypePrinter.pretty0 im (-1) tp
+          tm' <- avoidCapture (prettyBinding0 a v tm)
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Syntax/TermPrinter.hs:822]: This is the real meat of the fix. If the type binds type variables, they are bound in the scope of the lambda it annotates. I'm avoiding capture of those variables by adding them to the `local` scope. `addTypeVars` calls `local` which means these variables will go out of scope when the printer for the binding is finished.

File: parser-typechecker/src/Unison/Syntax/TypePrinter.hs [hunk 7]
```diff
@@ -71,90 +73,103 @@ prettyStr Nothing n t =
...
-                        `PP.hang` go n im (-1) body
+            prettyForall p = do
+              let vformatted = PP.sep " " (fmt S.Var . PP.text . Var.name <$> vs)
+              PP.hang (fmt S.TypeOperator "∀ " <> vformatted <> fmt S.TypeOperator ".") <$> go im p body
+         in -- if we're printing a type signature, and all the type variables
+            -- are universally quantified, then we can omit the `forall` keyword
+            -- only if the type variables are not bound in an outer scope
+            if p < 0 && all Var.universallyQuantifyIfFree vs
+              then ifM (willCapture vs) (prettyForall p) (go im p body)
+              else paren (p >= 0) <$> prettyForall (-1)
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Syntax/TypePrinter.hs:128]: This is where I'm checking (with `willCapture`) whether we need to add the `forall` keyword here to avoid capture of type variables bound in the outer scope.

**Comment by ceedubs** [comment]
@runarorama wow! I had no idea that this would be such an involved change. I'm not familiar enough with this code to be a good reviewer but I just wanted to say thank you! 🎉🙏

File: parser-typechecker/src/Unison/Typechecker/Context.hs [hunk 8]
```diff
@@ -326,13 +326,13 @@ removeSyntheticTypeVars typ =
...
-              put (Set.insert v' used, Map.insert v v' curMappings)
-              pure v'
-            Just v' -> pure v'
+        (used, curMappings) <- get
+        case Map.lookup v curMappings of
+          Nothing -> do
+            let v' = pickName used (Var.typeOf v)
+            put (Set.insert v' used, Map.insert v v' curMappings)
+            pure v'
+          Just v' -> pure v'
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/Typechecker/Context.hs]: Hmm, it looks like this whole file was reformatted, but there no substantive changes? I'd maybe revert, since @tstat has a branch in progress that does surgery on this file to add pattern coverage checking and I'm concerned about it being a mess to merge.

File: unison-cli/src/Unison/CommandLine/DisplayValues.hs [hunk 9]
```diff
@@ -246,10 +246,9 @@ displayPretty pped terms typeOf eval types tm = go tm
       typeOf r >>= \case
         Nothing -> pure $ termName (PPE.suffixifiedPPE pped) r
         Just typ ->
-          pure . P.group $
-            TypePrinter.prettySignaturesCTCollapsed
-              (PPE.suffixifiedPPE pped)
-              [(r, PPE.termName (PPE.suffixifiedPPE pped) r, typ)]
+          pure . P.group
+            . runPretty (PPE.suffixifiedPPE pped)
+            $ TypePrinter.prettySignaturesCTCollapsed [(r, PPE.termName (PPE.suffixifiedPPE pped) r, typ)]
```
Comment (pchiusano) [inline unison-cli/src/Unison/CommandLine/DisplayValues.hs]: I find it a bit awkward to have to import this other module providing `MonadPretty` whose only purpose here is to allow you to pass in the `PrettyPrintEnv`. Like, as a user, I just want that to pass the `PrettyPrintEnv` as another argument to the pretty-printer.

WDYT of folding the `runPretty` into the public interface of the pretty-printer, so users of the prettyprinter don't even need to be aware of the fact that it uses some monad they don't care about internally. Then there'd be no diff at all in this file or any other file that calls into the pretty-printer.

So like, in `TypePrinter` you'd have `prettySignaturesCTCollapsedImpl` which can use `MonadPretty` internally, and then a version without `impl` on the end which has the same signature as now and calls into the implementation and does the `runPretty` for you.

File: parser-typechecker/src/Unison/Syntax/TypePrinter.hs (hunk 7 above)
Comment (pchiusano) [reply parser-typechecker/src/Unison/Syntax/TypePrinter.hs:128]: Makes sense.

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs (hunk 6 above)
Comment (pchiusano) [reply parser-typechecker/src/Unison/Syntax/TermPrinter.hs:822]: Yup, makes sense.

**Review by pchiusano — DISMISSED** [review]
Cool. At first I was like "why the heck is this diff so big??", but I get it, we need to plumb some additional state around to track what type variables are in scope, and easiest way to do that is with a monad. 

However, can you at least look at reverting the misc reformatting to `Context.hs` since I'm worried that might conflict with other major surgery that's happening there.

I also left a WDYT suggestion on keeping the same interface to the pretty-printer rather than requiring users to import and use this `MonadPretty` thing just to supply the `PrettyPrintEnv`.

File: parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs (hunk 3 above)
Comment (ChrisPenner) [reply parser-typechecker/src/Unison/PrettyPrintEnv/MonadPretty.hs:12]: Most instances can be derived these days with `deriving via` and newtype deriving, but this is good too 👍🏼 

I would prefer using a record for the env, since it's pretty likely to expand over time and all of the `view _1`'s can get pretty confusing when it gets bigger; not a deal-breaker though.

File: parser-typechecker/src/Unison/Syntax/TermPrinter.hs (hunk 5 above)
Comment (ChrisPenner) [reply parser-typechecker/src/Unison/Syntax/TermPrinter.hs:166]: Yeah, there's a pretty good chance the pretty-printer will eventually read names directly from Sqlite on demand, so we'll need a pretty-print monad at that point anyways. Thanks for getting a good head-start on it 👍🏼

File: unison-share-api/src/Unison/Server/Backend.hs [hunk 10]
```diff
@@ -1096,9 +1101,9 @@ scopedNamesForBranchHash codebase mbh path = do
     Nothing
       | shouldUseNamesIndex -> indexNames
       | otherwise -> do
-          rootBranch <- lift $ Codebase.getRootBranch codebase
-          let (parseNames, _prettyNames, localNames) = namesForBranch rootBranch (AllNames path)
-          pure (parseNames, localNames)
+        rootBranch <- lift $ Codebase.getRootBranch codebase
```
Comment (ChrisPenner) [inline unison-share-api/src/Unison/Server/Backend.hs:1103]: If possible it'd be great if you could upgrade your ormolu to 4.0.0.0 to avoid formatter battles; it's what all of the UCM team are using at the moment 😄

**Review by ChrisPenner — APPROVED** [review]
I mostly skimmed it, but seems like it's mostly just piping things through 👍🏼 

Could you add a transcript which demos the new quantifier behaviour to avoid regressions in the future?

File: parser-typechecker/src/Unison/Typechecker/Context.hs (hunk 8 above)
Comment (runarorama) [reply parser-typechecker/src/Unison/Typechecker/Context.hs]: I'm the first to change this file since ormolu came into the stack so that's probably why the whole thing got reformatted

File: unison-cli/src/Unison/CommandLine/DisplayValues.hs (hunk 9 above)
Comment (runarorama) [reply unison-cli/src/Unison/CommandLine/DisplayValues.hs]: That's already the case. There's a number of public functions that call runpretty for you, but this particular call site wants some special handling (CTCollapsed, whatever that means)

File: parser-typechecker/src/Unison/Typechecker/Context.hs (hunk 8 above)
Comment (pchiusano) [reply parser-typechecker/src/Unison/Typechecker/Context.hs]: I don't think that's true. The whole codebase got ormolu'd. I suspect you're just using a different version of ormulu like @ChrisPenner said. Can you please update and refresh, and then it'll be easier to review (and should be at less risk of conflicts with other changes to the file).

File: unison-cli/src/Unison/CommandLine/DisplayValues.hs (hunk 9 above)
Comment (pchiusano) [reply unison-cli/src/Unison/CommandLine/DisplayValues.hs]: I was suggesting that no public API call site should have to change, including this one. As in, the pretty-printer has a public API (which includes this `prettySignaturesCTCollapsed`) and the type signatures of those functions could be kept identical to what they were before this PR. But maybe since this one is pretty special purpose it doesn't matter so much.

Comment (runarorama) [reply unison-cli/src/Unison/CommandLine/DisplayValues.hs]: I basically don't think we can get away with that for the long term. Ultimately the pretty-printer will be doing monadic stuff to get its own type names and term names, so it'll have to run in some transformer over `IO` or whatever and callers will have to change anyway.

**Comment by runarorama** [comment]
> I mostly skimmed it, but seems like it's mostly just piping things through 👍🏼
> 
> Could you add a transcript which demos the new quantifier behaviour to avoid regressions in the future?

I added a unit test in the regular TermPrinter test suite, no transcript required.
