### PR TITLE
Fixes to suffix-based name resolution when local file names shadow codebase names

### LINKED ISSUE #3759: Suffix-based resolution picks name in codebase instead of file
In your codebase, have a definition `Foo.state`. 

Then in the file, have `type Blah = { state : Nat} ` and use `state` unqualified. It picks the `Foo.state` in the codebase.

Another example - in the codebase, have a type `blah.Foo`, then in your scratch file have:

```
unique type OoogaBooga.Foo = Foo Text

unique ability Blah where
  foo : Foo -> ()

oog = do 
  foo 42
```

It resolves the `Foo` type suffix there to the codebase `blah.Foo` rather than the `OogaBooga.Foo` that's declared in the scratch file.

### PR DESCRIPTION
**Pull request by pchiusano**
Fixes #3759 which was actually two unrelated bugs.
Closes #3976

The more serious bug here was that type signatures in data declarations wouldn't prefer local names using a unique suffix. So if you had `Foo.Blah` as a type in your codebase and `Oog.Blah` in your file, the type `Blah` would actually resolve to `Foo.Blah`. This could generate serious WTFs especially when doing updates of a type and related functions.

This fixes that, and also an issue where record accessors weren't being considered for local suffix-based name resolution.

I added regression tests for everything. I also confirmed that these regression tests all failed before making the fixes.

## Implementation notes

I added a function `variableCanonicalizer` which, given a set of variables, maps unique suffixes. This logic is sort of fancy and was for some reason just inlined in the file parser. I pulled it out into a function which is now called to deal with type and term suffix resolution.

### CODE REVIEW

File: parser-typechecker/src/Unison/Syntax/FileParser.hs [hunk 1]
```diff
@@ -42,14 +41,21 @@ file = do
...
     Right (Right env) -> pure env
     Right (Left es) -> P.customFailure $ TypeDeclarationErrors es
     Left es -> resolutionFailures (toList es)
+  let accessors :: [[(v, Ann, Term v Ann)]]
+      accessors =
+          [ DD.generateRecordAccessors (toPair <$> fields) (L.payload typ) r
+            | (typ, fields) <- parsedAccessors,
+              Just (r, _) <- [Map.lookup (L.payload typ) (UF.datas env)]
+          ]
+      toPair (tok, typ) = (L.payload tok, ann tok <> ann typ)
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/Syntax/FileParser.hs:54]: This was moved up from below unchanged so that we'll have the names of all record field accessors and can have those names participate in suffix-based resolution.

File: parser-typechecker/src/Unison/Syntax/FileParser.hs [hunk 2]
```diff
@@ -69,58 +75,38 @@ file = do
...
+            canonicalVars = UFN.variableCanonicalizer fqLocalTerms
+            
+            -- All unique local term name suffixes - these we want to
+            -- avoid resolving to a term that's in the codebase
+            locals :: [Name.Name]
+            locals = (Name.unsafeFromVar <$> Map.keys canonicalVars)
+            
+            -- A function to replace unique local term suffixes with their
+            -- fully qualified name
+            replacements = [ (v, Term.var () v2) | (v,v2) <- Map.toList canonicalVars, v /= v2 ]
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/Syntax/FileParser.hs:100]: This code was greatly simplified, calling out to `UFN.variableCanonicalizer` for the heavy lifting.

**Review by pchiusano — COMMENTED** [review]
Self review

**Comment by pchiusano** [comment]
Oops, I didn't even see #3976 but I think this PR likely obsoletes that. 😬 Sorry about that @ChrisPenner I probably could have at least used your transcript as a starting point for the regression test.

**Comment by ChrisPenner** [comment]
No worries @pchiusano , that PR is literally just the captured transcript for if I ever got around to implementing the fix, stoked that I can close it 🙌🏼

**Review by aryairani — APPROVED** [review]

**Comment by aryairani** [comment]
👍
