### PR TITLE
Fix #3861

### LINKED ISSUE #3861: UnkownDecl error in record type
This code

```
unique type Foo = {
  i : Instant
}
```

Gives this error:

```
  UnknownDecl:
    data type
    reference = Instant
```

This works fine though:

```
unique type Foo = Foo Instant
```

As does this:

```
unique type Foo = {
  i : Text
}
```

### PR DESCRIPTION
**Pull request by tstat**
## Overview

There is another typechecking codepath that seeded the `TypeLookup` building function with `Term.dependencies` instead of `UnisonFile.dependencies`, so it didn't fetch data decl dependencies.

### CODE REVIEW

**Review by mitchellwrosen — APPROVED** [review]

File: parser-typechecker/src/Unison/FileParsers.hs [hunk 1]
```diff
@@ -96,17 +96,14 @@ resolveNames ::
     (Term v, TDNRMap v, TL.TypeLookup v Ann)
 resolveNames typeLookupf preexistingNames uf = do
   let tm = UF.typecheckingTerm uf
```
Comment (aryairani) [inline parser-typechecker/src/Unison/FileParsers.hs:98]: Do we like maybe even moving `tm` into the list comprehension?

**Review by aryairani — APPROVED** [review]

**Review by pchiusano — APPROVED** [review]
