### PR TITLE
Fix suffixification bug #4424

### LINKED ISSUE #4424: overly suffixified constructor when names are split across codebase and scratch file?
Derived from https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1700598328218529

Transcript gist: https://gist.github.com/aryairani/c9a3e5f98b0828c2b3aced05b2fe216c

## Transcript output:

```unison
unique type Cat.Dog = Mouse Nat
unique type Rat.Dog = Bird

countCat = cases
  Cat.Dog.Mouse x -> Bird
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    unique type Cat.Dog
    unique type Rat.Dog
    countCat : Cat.Dog -> Rat.Dog

```
Now I want to add a constructor.

```unison
unique type Rat.Dog = Bird | Mouse
```

```ucm
.> update

  Okay, I'm searching the branch for code that needs to be
  updated...

  That's done. Now I'm making sure everything typechecks...

  countCat : Cat.Dog -> Rat.Dog
  countCat = cases Mouse x -> Bird
  
  unique type Rat.Dog = Bird | Mouse

  Typechecking failed. I've updated your scratch file with the
  definitions that need fixing. Once the file is compiling, try
  `update` again.

```
Here's the code that `update` produced:

```unison
countCat : Cat.Dog -> Rat.Dog
countCat = cases Mouse x -> Bird

unique type Rat.Dog = Bird | Mouse
```

```ucm

  This pattern has the wrong number of arguments
  
      2 | countCat = cases Mouse x -> Bird
  
  The constructor has type 
  
    Rat.Dog
  
  but you supplied 1 arguments.

```
This code should have type-checked without user intervention, but the way it printed `cases Mouse x` is ambiguous, and UCM assumed `Mouse` meant `Rat.Dog.Mouse` instead of `Cat.Dog.Mouse`, which failed.

I'll fix it by making it explicit:

```unison
countCat : Cat.Dog -> Rat.Dog
countCat = cases Cat.Dog.Mouse x -> Bird

unique type Rat.Dog = Bird | Mouse
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These names already exist. You can `update` them to your
      new definition:
    
      unique type Rat.Dog
      countCat : Cat.Dog -> Rat.Dog

```
Ok, all set! Now let's update.

```ucm
.> update

  Okay, I'm searching the branch for code that needs to be
  updated...

  That's done. Now I'm making sure everything typechecks...

  countCat : Cat.Dog -> Rat.Dog
  countCat = cases Mouse x -> Rat.Dog.Bird
  
  unique type Rat.Dog = Bird | Mouse

  Typechecking failed. I've updated your scratch file with the
  definitions that need fixing. Once the file is compiling, try
  `update` again.

```
Why is it still ambiguous?

Thanks @alvaroc1 for reporting.

### PR DESCRIPTION
**Pull request by tstat**
## Overview

During update we create a unison file containing the updates as well as the dependents of things to be updated. We print both the old and new references updates with the same name then typecheck this constructed file to see if the updated codebase will typecheck.

So, we want both the old and new references of updates to be printed with the same name. This was achieved previously through `addFallback`, which accomplished that goal, but introduced other problems. The problem demonstrated by #4424 is that the two arguments of `addFallback` are suffixified separately, so, if a suffixified name in one arg is a suffix of a name in the other arg, then parsing is ambiguous.

This PR replaces the use of `addFallback` with a new function `shadowNames` that suffixifies the combined names, but ensures that the updated terms are printed unqualified.

Fixes #4424 

## Test coverage

There is a new transcript that demonstrates 4424, followed by a commit that fixes it.

### CODE REVIEW

File: unison-core/src/Unison/NamesWithHistory.hs [hunk 1]
```diff
@@ -38,7 +38,7 @@ data NamesWithHistory = NamesWithHistory
 
 instance Semigroup NamesWithHistory where
   NamesWithHistory cur1 old1 <> NamesWithHistory cur2 old2 =
-    NamesWithHistory (cur1 <> old1) (cur2 <> old2)
```
Comment (tstat) [inline unison-core/src/Unison/NamesWithHistory.hs:41]: This is a different bug that ran into while writing `shadowNames`.

**Review by aryairani — APPROVED** [review]
