### PR TITLE
Fix duplicate find_type(_mentions)_index entries

### LINKED ISSUE #2332: find_type_mentions_index table has redundant rows
I was exploring why the database for my codebase is so large and found that the `find_type_mentions_index` table is the largest. Looking at this table it seems that there are many duplicate rows. Here's the table schema:

```
sqlite> .schema find_type_mentions_index
CREATE TABLE find_type_mentions_index (
  type_reference_builtin INTEGER NULL CONSTRAINT find_type_mentions_index_fk1 REFERENCES text(id),
  type_reference_hash_id INTEGER NULL CONSTRAINT find_type_mentions_index_fk2 REFERENCES hash(id),
  type_reference_component_index INTEGER NULL,
  term_referent_object_id INTEGER NOT NULL CONSTRAINT find_type_mentions_index_fk3 REFERENCES object(id),
  term_referent_component_index INTEGER NOT NULL,
  term_referent_constructor_index INTEGER NULL,
  CONSTRAINT find_type_mentions_index_c1 CHECK (
    (type_reference_builtin IS NULL) =
    (type_reference_hash_id IS NOT NULL)
  ),
  CONSTRAINT find_type_mentions_index_c2 CHECK (
    (type_reference_hash_id IS NULL) =
    (type_reference_component_index IS NULL)
  )
);
CREATE INDEX find_type_mentions_index_type ON find_type_mentions_index (
  type_reference_builtin,
  type_reference_hash_id,
  type_reference_component_index
);
```

When I count the number of rows in the table:

```
sqlite> select count(*) from find_type_mentions_index;
696323
```

and the number of unique rows in the table:

```
sqlite> select count(*) from (select distinct type_reference_builtin,type_reference_hash_id,type_reference_component_index, term_referent_object_id,term_referent_component_index ,term_referent_constructor_index from find_type_mentions_index);
44389
```

We find that the table is 15 times as large as it needs to be:
```
sqlite> select 696323.0 / 44389;
15.6868368289441
```

And note that this table and its index make up more than 50% of the data in our database!

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

This PR fixes #2332.

We had duplicate rows in the `find_type_index` and `find_type_mentions_index` due to code that looked like:

```
for each member of a component,
  do some per-member stuff
  copy over the whole component's index rows
```

which was de-dented to become

```
for each member of a component,
  do some per-member stuff
copy over the whole component's index rows
```

Additionally, to guard against syncing from old databases that have this property, we now `nubOrd` the list index rows before copying over. As mentioned in a comment in the source, this could also be accomplished by putting a unique index on the index tables for the whole 6-tuple, if we want to do that some day.

## Test coverage

No automated tests were added. I did manually confirm this PR passes the Stew Test from #2332:

```
sqlite> select count(*) from find_type_index;
19206
sqlite> select count(*) from (select distinct type_reference_builtin,type_reference_hash_id,type_reference_component_index, term_referent_object_id,term_referent_component_index ,term_referent_constructor_index from find_type_index);
19206
sqlite> select count(*) from find_type_mentions_index;
112326
sqlite> select count(*) from (select distinct type_reference_builtin,type_reference_hash_id,type_reference_component_index, term_referent_object_id,term_referent_component_index ,term_referent_constructor_index from find_type_mentions_index);
112326
```

Note we have two pairs of equal numbers. Previously, the `count(*)` was far greater than the distinct `count(*)` on this database I'm testing against.

### CODE REVIEW

**Review by pchiusano — APPROVED** [review]
Wow, good catch.

It might be nice to have a "rebuild index" command at some point. 

Would one way to repair an existing codebase is just to push its root to an empty codebase? And then the `nubOrd` will take care of deduping, and then going forward `ucm` won't produce duplicates.

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs [hunk 1]
```diff
@@ -167,26 +167,21 @@ trySync tCache hCache oCache cCache = \case
...
+                -- sync watch results
+                for_ [WK.TestWatch] \wk ->
+                  syncWatch wk (Reference.Id hId idx)
+                -- sync dependencies index
+                let ref = Reference.Id oId idx
+                    ref' = Reference.Id oId' idx
+                let fromJust' = fromMaybe (error "missing objects should've been caught by `foldLocalIds` above")
+                runSrc (Q.getDependenciesForDependent ref)
+                  >>= traverse (fmap fromJust' . isSyncedObjectReference)
+                  >>= runDest . traverse_ (flip Q.addToDependentsIndex ref')
```
Comment (aryairani) [inline codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs]: We should split this and the other spot into its own `syncDependenciesIndex` function too, to match. Can be here or a separate PR after.

**Review by aryairani — APPROVED** [review]
Awesome! Go ahead and merge when ready.

**Comment by aryairani** [comment]
@mitchellwrosen So is it correct that a codebase with existing bloat can be fixed by pushing the whole thing somewhere and the pulling to a new codebase?  /cc @stew 

This workaround is also a temporary one, because all codebases will have their indexes fixed during the codebase schema migration.

**Comment by mitchellwrosen** [comment]
@pchiusano / @aryairani Yeah, that'd work (at least in my head)

**Comment by aryairani** [comment]
Funny, I totally missed that Paul had already asked the same question.

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs (hunk 1 above)
Comment (mitchellwrosen) [reply codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs]: I added this in https://github.com/unisonweb/unison/pull/2538/commits/0f7b20d921a28b0b829ecc436819bf04fc30c9ed, and pulled in `unison-prelude` as a dependency of `codebase-sqlite`, which I think is ok, because it should be at the root of everything and not contain anything parser-typechecker specific.

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs [hunk 2]
```diff
@@ -346,6 +339,13 @@ trySync tCache hCache oCache cCache = \case
     isSyncedObjectReferenceId (Reference.Id oId idx) =
       isSyncedObject oId <&> fmap (\oId' -> Reference.Id oId' idx)
 
+    -- Assert that a reference's component is already synced, and return the corresponding reference.
+    expectSyncedObjectReference :: Sqlite.Reference -> m Sqlite.Reference
+    expectSyncedObjectReference ref = undefined
+      isSyncedObjectReference ref <&> \case
+        Nothing -> error (reportBug "E452280" ("unsynced object reference " ++ show ref))
+        Just ref' -> ref'
+
```
Comment (aryairani) [inline codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs]: I'm surprised no existing push-pull tests failed on this `undefined`, what am I missing?

**Review by aryairani — CHANGES_REQUESTED** [review]

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs (hunk 2 above)
Comment (aryairani) [reply codebase2/codebase-sqlite/U/Codebase/Sqlite/Sync22.hs]: Disregard; they did fail on this `undefined`.

**Review by aryairani — APPROVED** [review]

**Review by ChrisPenner — APPROVED** [review]
Thanks for doing this; I think this provides us with at least two object lessons:

1. Aggressively pull out helpers so that the control-flow and nesting at the top level becomes clear (e.g. operate at a single layer of abstraction at a time)
2. Add as many unique indexes as we can, even if we _think_ we don't need them

**Comment by aryairani** [comment]
> 2. Add as many unique indexes as we can, even if we _think_ we don't need them

I'd push back on this somewhat — I suspect I left this out on purpose to reduce the size of the index on disk (and I'd want to do a space comparison before adding it back in), though in that case I ought to have left a comment with some concrete numbers.

Or, I should have added the unique constraint during development & testing, and then dropped it before releasing it to the public, which would have caught this bug too.
