### PR TITLE
Fix to subtle name resolution bug that results in using TDNR unexpectedly

### LINKED ISSUE #2353: Why is TDNR getting used in this example?
Here’s a self-contained example:

```
use builtin Scope
unique ability Async t g where async : Nat
unique ability Exception where raise : Nat -> x

pure.run : a -> (forall t . '{Async t g} a) ->{Exception, g} a
pure.run a0 a = 
  a' : forall s . '{Scope s, Exception, g} a
  a' = 'a0 -- typechecks
  Scope.run a'
```
This yields:
```
  I'm not sure what Scope.run means at line 10, columns 3-12
  
     10 |   Scope.run a'
  
  Whatever it is, it has a type that conforms to (Unit ->{g, 𝕖, Exception, builtin.Scope s} a) -> a.
  I found a term in scope with a matching name but a different type. If this is what you meant, try using the fully qualified name and I might be able to give you a more illuminating error message: 
  
    - .builtin.Scope.run : (Unit ->{builtin.Scope s, g} r) ->{g} r
```
Changing this to `##Scope.run a’` causes it to work, so it seems like some sort of name resolution failure - basically, it isn’t resolving `Scope.run` to a definition and is instead resorting to TDNR to figure out what definition it is.

Scope.run is a unique suffix in my codebase (according to `find Scope.run`, which only returns 1 result), so I don’t know what’s going on.

I kinda want to dig into this, since it could result in a lot of weird typechecking issues if unique suffixes aren’t being resolved properly.

### PR DESCRIPTION
**Pull request by pchiusano**
Fixes #2353 and adds a regression test.

The bug was resulting in use of the TDNR code path for more cases than expected. I'm still not totally sure what the implications are of the old behavior, since the TDNR code path has a short circuit if a definition has a unique suffix and the right type.

This fix avoids TDNR for the use case that was given and all the other transcripts are unchanged, including [this one](https://github.com/unisonweb/unison/blob/trunk/unison-src/transcripts/fix1578.output.md) which checks various subtle cases of name resolution.

Filed a separate bug for https://github.com/unisonweb/unison/issues/2381

### CODE REVIEW

File: parser-typechecker/src/Unison/FileParser.hs [hunk 1]
```diff
@@ -92,19 +95,22 @@ file = do
           -- suffix, but `bob` is. `foo.alice` and `bob.alice` are both unique suffixes but
           -- they map to themselves, so we ignore them. In our example, we'll just be left with
           --   [(bob, Term.var() zonk.bob)]
-          replacements = [ (Name.toVar n, Term.var() v') | (n,[v']) <- Map.toList varsBySuffix
-                                                         , Name.toVar n /= v' ]
+          replacements = [ (Name.toVar n, Term.var() v')
+                         | (n, nubOrd -> [v']) <- Map.toList varsBySuffix
+                         , Name.toVar n /= v' ]
```
Comment (pchiusano) [inline parser-typechecker/src/Unison/FileParser.hs:100]: Missing `nubOrd` would cause this logic to not fire for any name with multiple segments. This was wrong.

File: unison-core/src/Unison/Names3.hs [hunk 2]
```diff
@@ -311,13 +311,13 @@ expandWildcardImport prefix ns =
...
 -- resolution where local names are preferred to codebase names.
-shadowSuffixedTerms0 :: [Name] -> Names0 -> Names0
-shadowSuffixedTerms0 ns n0 = names0 terms' (types0 n0)
+shadowTerms0 :: [Name] -> Names0 -> Names0
+shadowTerms0 ns n0 = names0 terms' (types0 n0)
   where
-  shadowedBy name = Name.searchBySuffix name (terms0 n0)
-  terms' = R.subtractRan (foldMap shadowedBy ns) (terms0 n0)
+  terms' = foldl' go (terms0 n0) ns
+  go ts name = R.deleteDom name ts
```
Comment (pchiusano) [inline unison-core/src/Unison/Names3.hs:323]: This function no longer needs to do any fancy suffix-based stuff, so I renamed and simplified it. It wasn't being called anywhere else besides the name resolution code.

**Comment by pchiusano** [comment]
It's also likely this speeds up typechecking since the TDNR codepath is kinda slow, even when there's unique matches.

**Comment by ceedubs** [comment]
I'm not well-versed enough in the compiler to be able to offer a meaningful review, but thanks, for fixing this, @pchiusano. I ran into this over the weekend and was stumped for quite a while. I was working with some funky types, so I thought that I just didn't have the types lining up properly.

**Comment by aryairani** [comment]
I'm not really sure how to evaluate this either, but I think it demonstrates the need for a boring comprehensive set of transcripts that fully spec out the behavior of TDNR. (Can be a separate effort.)  LMK if you want to walk through the PR together or if you want me to rubber-stamp it; and I'll leave it for @runarorama to take a look at in the mean time.

**Comment by pchiusano** [comment]
@aryairani I'd just do a rubber stamp. If we do a walkthrough it'll soon be forgotten. :) I think we should task the next person who has to do surgery on this code to produce a writeup of how name resolution works. :)

I kind of want to just rethink TDNR and don't really want to expend effort trying to document exactly how it works right now. It's unpredictable and often not useful if your program has any type errors. See old discussion in https://github.com/unisonweb/unison/issues/448. I don't think addressing that is top priority right now, but if we were going to exhaustively document something, I'd want it to be a more predictable algorithm than what's there now.

**Review by aryairani — APPROVED** [review]
Makes sense.

**Review by runarorama — APPROVED** [review]

**Comment by ceedubs** [comment]
I can confirm that this solves the nasty issue that I was running into where I got a cryptic error if I named my function `fold` but it was fine if I called it `fold2`. 🥳
