### PR TITLE
Add parens around let blocks, fix delayed effect parser

### LINKED ISSUE #1778: Round trip fails for parenthesised let block + operator
`ucm version: release/M1m`

Place this code in scratch.u:
```
x = '(let
  abort
  0) |> Abort.toOptional
```

Then
```
>. update
>. edit x
```
prepends to scratch.u:
```
x : Optional Nat
x =
  'let
    abort
    0 |> toOptional
```
which is different and doesn't typecheck.

### PR DESCRIPTION
**Pull request by runarorama**
Fixes #1778 

This adds parens around delayed et blocks that appear as arguments to operators.

```
x = ('let
  abort
  0) |> Abort.toOptional

y = (let
        x = 10
        x + 2) |> id
```

Also fixes the type parser so that it allows the following:

```
x -> '{Abort} Optional a 
```

instead of requiring

```
x -> '{Abort} (Optional a)
```

### CODE REVIEW

File: parser-typechecker/src/Unison/Parser.hs [hunk 1]
```diff
@@ -53,6 +54,7 @@ import qualified Unison.Hashable as Hashable
 import Unison.Referent (Referent)
 import Unison.Reference (Reference)
 import Unison.Parser.Ann (Ann(..))
+import Text.Megaparsec.Error (ShowErrorComponent)
```
Comment (runarorama) [inline parser-typechecker/src/Unison/Parser.hs:57]: This is added purely for debugging. No harm in having this.

File: parser-typechecker/src/Unison/TermPrinter.hs [hunk 2]
```diff
@@ -368,7 +368,7 @@ pretty0
            -> ([Pretty SyntaxText] -> Pretty SyntaxText)
            -> Pretty SyntaxText
   printLet elideUnit sc bs e im uses =
-    paren ((sc /= Block) && p >= 12)
+    paren ((sc /= Block) && p >= 3)
```
Comment (runarorama) [inline parser-typechecker/src/Unison/TermPrinter.hs]: This will cause parens to print around a `let` block if it appears as an argument to a function.

File: parser-typechecker/src/Unison/TypeParser.hs [hunk 3]
```diff
@@ -72,7 +72,7 @@ type2 = do
 effect :: Var v => TypeP v
 effect = do
  es <- effectList
- t <- valueTypeLeaf
+ t <- type2
```
Comment (runarorama) [inline parser-typechecker/src/Unison/TypeParser.hs:75]: This allows `'{Foo} Optional a` instead of requiring `'{Foo} (Optional a)`

File: parser-typechecker/src/Unison/TypePrinter.hs [hunk 4]
```diff
@@ -109,37 +109,37 @@ prettyRaw n im p tp = go n im p tp
...
   arrows delay first ((mes, arg) : rest) =
-    arrow delay first mes
-      <> (  parenNoGroup (delay && (not $ null rest))
-         $  go n im 0 arg
-         <> arrows False False rest
-         )
+    arrow delay first mes <> parenNoGroup
+      (delay && not (null rest))
+      (go n im 0 arg <> arrows False False rest)
+
```
Comment (runarorama) [inline parser-typechecker/src/Unison/TypePrinter.hs:134]: These changes are just for readability to help me understand this code. Small improvement.

**Review by pchiusano — APPROVED** [review]
👍

CI is failing - looks like unit tests need updating.

File: unison-src/transcripts-round-trip/main.output.md [hunk 5]
```diff
@@ -34,15 +34,15 @@ x = 1 + 1
   most recent, along with the command that got us there. Try:
   
     `fork 2 .old`             
-    `fork #bt17giel42 .old`   to make an old namespace
+    `fork #m41m2ql36i .old`   to make an old namespace
```
Comment (aryairani) [inline unison-src/transcripts-round-trip/main.output.md:37]: Do we expect changed hashes here?

Comment (runarorama) [reply unison-src/transcripts-round-trip/main.output.md:37]: I don't know why this changes. The transcript is starting up with a different root hash than before for some reason.

Comment (runarorama) [reply unison-src/transcripts-round-trip/main.output.md:37]: This happens in trunk as well, so it's unrelated to this change.

Comment (aryairani) [reply unison-src/transcripts-round-trip/main.output.md:37]: Oh weird, ok.

**Comment by pchiusano** [comment]
@runarorama adding the round-trip tests to `stack exec transcripts` will cause CI to fail every time.

There's a separate CI target for the round trip tests, which is run automatically by CI (see [this commit](https://github.com/unisonweb/unison/pull/2385/commits/2ab39a2ac4786e99c4fc3a7bfbf4513353b2c612)). You might want to define an alias for the command it's running.

The reason for the separation is that CI checks that the working directory is clean after running `stack exec transcripts` (to catch transcript changes). The working dir won't be clean after the round trip tests are dumping definitions to a scratch file. We also can't check in the scratch file produced by round-tripping since running the round trip test will push definitions at the top of the scratch file (i.e., it's not idempotent in how it updates the scratch file, nor could it be).

If you don't like that, another option might be to have CI somehow delete the scratch file after running the transcript... we just don't want to be deleting files called `scratch.u` in the developer's working directory. :)
