### PR TITLE
Handle failing to open a remote codebase better

### LINKED ISSUE #2694: UCM should not consider a remote codebase that fails to open equivalent to an empty codebase
In working on <oops, missing ticket>, I discovered that when viewing a remote codebase, if it fails to open for any reason (including a schema version too high), we consider it to be empty instead. There's a comment that indicates this seems wrong. I think it is too =)

### PR DESCRIPTION
**Pull request by mitchellwrosen**
## Overview

This PR changes the behavior of `viewRemoteBranch` to no longer consider any failure to open the codebase whatsoever, including if the remote codebase is at an unknown schema version, as if the remote branch was empty.

On trunk, attempting to pull a remote codebase with an unknown schema prints this: 

Screenshot from 2021-12-01 20-44-05

On this branch, it prints this:

Screenshot from 2021-12-01 20-40-33

Additionally, we also now have a nicer error message for when there's no codebase there at all:

Screenshot from 2021-12-01 20-49-56

On trunk, this just crashes with an uncaught exception from sqlite. 

Fixes #2694

## Test coverage

I tested this change manually.

### CODE REVIEW

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 1]
```diff
@@ -1057,43 +1045,51 @@ viewRemoteBranch' ::
...
-        Right inner -> pure inner
+  remotePath <- UnliftIO.fromEitherM . runExceptT . withExceptT C.GitProtocolError . time "Git fetch" $ pullBranch repo
+
+  -- Tickle the database before calling into `sqliteCodebase`; this covers the case that the database file either
+  -- doesn't exist at all or isn't a SQLite database file, but does not cover the case that the database file itself is
+  -- somehow corrupt, or not even a Unison database.
+  --
+  -- FIXME it would probably make more sense to define some proper preconditions on `sqliteCodebase`, and perhaps update
+  -- its output type, which currently indicates the only way it can fail is with an `UnknownSchemaVersion` error.
+  (withConnection "" remotePath \_ -> pure ()) `catch` \sqlError ->
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs]:
```suggestion
  (withConnection "codebase exists check" remotePath \_ -> pure ()) `catch` \sqlError ->
```

**Review by ChrisPenner — APPROVED** [review]

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs [hunk 2]
```diff
@@ -1057,43 +1045,51 @@ viewRemoteBranch' ::
...
-        Left schemaVersion -> throwIO . C.GitSqliteCodebaseError $ GitError.UnrecognizedSchemaVersion repo remotePath schemaVersion
-        Right inner -> pure inner
+  remotePath <- UnliftIO.fromEitherM . runExceptT . withExceptT C.GitProtocolError . time "Git fetch" $ pullBranch repo
+
+  -- Tickle the database before calling into `sqliteCodebase`; this covers the case that the database file either
+  -- doesn't exist at all or isn't a SQLite database file, but does not cover the case that the database file itself is
+  -- somehow corrupt, or not even a Unison database.
+  --
+  -- FIXME it would probably make more sense to define some proper preconditions on `sqliteCodebase`, and perhaps update
+  -- its output type, which currently indicates the only way it can fail is with an `UnknownSchemaVersion` error.
```
Comment (aryairani) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase.hs:1057]: 👍

**Review by aryairani — APPROVED** [review]
I really wish Github diff could handle indentation changes better.
