### PR TITLE
Fix unused-binding-detection in case patterns

### LINKED ISSUE #5247: LSP: unused binding false positive on match guard
**Describe and demonstrate the bug**

If a binding is used only in a match guard it is flagged as unused, even though this _is_ a type of usage.

Input:
````
foo = cases
  Some n | n > 0 -> "positive"
  _ -> "not positive"
````

Output:
````
■ Unused binding "n". Use the binding, or prefix it with an _ to dismiss this warning.
````

**Screenshots**

image

**Environment (please complete the following information):**
 - `ucm --version` "0.5.25"
 - OS/Architecture: x86 NixOS

### PR DESCRIPTION
**Pull request by ChrisPenner**
Fixes #5247 

## Overview

Previously the LSP would warn you of "unused bindings" if the binding was unused in EITHER the guard OR the body, and also didn't correctly handle cases where you had several guards attached to a single pattern.

E.g. before:

image

Now, it doesn't produce an error in that case at all.

This fixes that.

There was also an oversight in the pattern parser which would give a "Constructor not found" error if you tried to use something like `Some _blah`; so I added a case there to treat under-score prefixed pattern variables just like other pattern variables, (but they're special in the unused bindings checker)

## Implementation notes

The current format of match cases in the ABT makes this a bit annoying to handle properly, but basically I now batch up all the match-cases with an identical pattern (which _hopefully_ correspond to a single binding block) then batch up _all_ the var usages amongst them and subtract ALL those usages from the unused bindings.

## Test coverage

Added some additional case-match test cases.

## Loose ends

The annotations for pattern match bindings are a bit imprecise, so for now it will simply highlight the whole pattern section if there's an unused binding there, but the error mentions the var by name so it's not a big issue.
I can _probably_ fix this with a bunch of elbow grease, but for now it doesn't seem worth the effort tbh.

### CODE REVIEW

File: parser-typechecker/src/Unison/Syntax/TermParser.hs [hunk 1]
```diff
@@ -294,12 +294,13 @@ parsePattern = label "pattern" root
...
       where
         isLower = Text.all Char.isLower . Text.take 1 . Name.toText
+        isIgnored n = Text.take 1 (Name.toText n) == "_"
         die hq s = case L.payload hq of
           -- if token not hash qualified or uppercase,
           -- fail w/out consuming it to allow backtracking
           HQ.NameOnly n
             | Set.null s
-                && isLower n ->
+                && (isLower n || isIgnored n) ->
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Syntax/TermParser.hs:303]: Previously we'd fall through to `failCommitted` on a `_foo` pattern variable, when really we should treat it just like a regular pattern var.

**Review by aryairani — APPROVED** [review]

**Review by ceedubs — APPROVED** [review]
Just gave this a spin and it's working great for me!

**Comment by ChrisPenner** [comment]
Nix build is failing, looks like it's just:

>  No space left on device

So I'll go ahead and merge.
