### PR TITLE
remove metadata types from the in-memory branches

### LINKED ISSUE #4416: crash with `NeedTypeForBuiltinMetadata` on ucm startup
See `https://unisoncomputing.slack.com/archives/CF8D3DCP3/p1697048365160779` for some repro and code links.

```
arya@halp /tmp % ucm

  Now starting the Unison Codebase Manager (UCM)...


   _____     _             
  ö  ö  ö___ö_ö___ ___ ___ 
  ö  ö  ö   ö ö_ -ö . ö   ö
  ö_____ö_ö_ö_ö___ö___ö_ö_ö
  
  👋 Welcome to Unison!
  
  You are running version: release/M5h


  📚 Read the official docs at https://www.unison-lang.org/learn/
  
  Hint: Type 'projects' to list all your projects, or 'project.create' to start something new.

ambitious-chameleon/main> 
SqliteQueryException
    ä sql = "SELECT text FROM text WHERE id = ?"
    , params =
        Ä SQLInteger 129 Å
    , exception = NeedTypeForBuiltinMetadata "Nat.+"
    , callStack = ÄÅ
    , connection = Connection
        ä name = "main"
        , file = "/Users/arya/.unison/v2/unison.sqlite3"
        å
    , threadId = ThreadId 19
    å
```

### PR DESCRIPTION
**Pull request by aryairani**
## Overview

This pretty hackily resolves #4416, where ucm would crash if a codebase included a term with a builtin associated as metadata, because the types of metadata are needed when loading a branch, but the types of builtins were not available when loading a branch, due to current package boundaries.

Since our long-term plan is to remove metadata altogether, with metadata-related commands and output already having been deleted in #4574, #4428, #4333, it seemed like a poor use of time to reorganize the packages to support this situation, and instead this PR removes "metadata type" from in-memory data structures.

Metadata type is not part of the hashing function of namespaces, so this should not affect anything but make the codebase a bit more skeleton-ish and weird.

## Implementation notes

In `Unison.Codebase.Metadata`, we replace
```haskell
type Type = TypeReference
```
with
```haskell
type Type = ()
```

And then fix up the dependent spots.

I just realized it could have been a smaller diff except I also changed `U.Codebase.Branch.Type` from
```haskell
newtype MdValues = MdValues {unMdValues :: Map MetadataValue MetadataType} deriving (Eq, Ord, Show)
```
to
```haskell
newtype MdValues = MdValues {unMdValues :: Set MetadataValue } deriving (Eq, Ord, Show)
```

## Test coverage

Relying on existing tests to make sure no behaviors have changed.

### CODE REVIEW

File: parser-typechecker/src/Unison/Codebase/Metadata.hs [hunk 1]
```diff
@@ -9,15 +9,15 @@ where
...
 import Unison.Prelude
-import Unison.Reference (Reference)
+import Unison.Reference (TermReference)
 import Unison.Util.List qualified as List
 import Unison.Util.Relation qualified as R
 import Unison.Util.Star3 (Star3)
 import Unison.Util.Star3 qualified as Star3
 
-type Type = Reference
+type Type = () -- dummy value, intermediate phase of removing metadata altogether
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/Metadata.hs:18]: I'm a little confused, what's the purpose of keeping a dummy type here? Is this being used anywhere that we can't also just delete?

File: parser-typechecker/src/Unison/Codebase/SqliteCodebase/Conversions.hs [hunk 2]
```diff
@@ -530,9 +532,9 @@ branch2to1 branchCache lookupCT (V2.Branch.Branch v2terms v2types v2patches v2ch
           let facts = Set.singleton ref
               names = Relation.singleton ref name
               types :: Relation.Relation ref V1.Metadata.Type =
-                Relation.insertManyRan ref (fmap mdref2to1 (Map.elems mdvals)) mempty
+                Relation.insertManyRan ref (fmap (const ()) (Set.toList mdvals)) mempty
               vals :: Relation.Relation ref (V1.Metadata.Type, V1.Metadata.Value) =
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/Codebase/SqliteCodebase/Conversions.hs:536]: Could this just be `Relation.Relation ref V1.Metadata.Value` now?

**Review by ChrisPenner — COMMENTED** [review]
I'm in favour of the change, but am curious why it stops where it does and leaves metadata types as `()` rather than propagating the removal, can you explain a bit more about that please?

**Comment by aryairani** [comment]
> I'm in favour of the change, but am curious why it stops where it does and leaves metadata types as `()` rather than propagating the removal, can you explain a bit more about that please?

It was just the minimal patch to let https://github.com/unisonweb/unison/issues/4416 stop crashing, which I want because I haven't been able to open my codebase for over three months 😓.

The more comprehensive cleanup would be nice, and I did attempt that initially (i.e. eliminate `Metadata.Star` altogether), but it's a core part of the `V1.Branch` type, and it became a big refactor that started to feel like a waste of time given that we want to delete metadata altogether but can't until we're prepared to do a rehash migration.

File: parser-typechecker/src/Unison/Codebase/Metadata.hs (hunk 1 above)
Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/Metadata.hs:18]: I think we'd need to write a `Star2` type and drop the `Type` index here. It would be better, but it just felt like busywork that was already slated to be thrown out.

Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/Metadata.hs:18]: I got nerdsniped

Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/Metadata.hs:18]: an hour later and no end in sight... it doesn't help that HLS lied about what's safe to delete, when it hadn't loaded all the packages yet to know.

Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/Metadata.hs:18]: Alternative at https://github.com/unisonweb/unison/compare/topic/NeedTypeForBuiltinMetadata-more
I agree it is better, but in retrospect also agree with past self that it's hard to justify the time expenditure when it's going to be tossed anyway.

**Review by mitchellwrosen — APPROVED** [review]
