### PR TITLE
Parse share handles separate from name segments

### LINKED ISSUE #3690: share: handles with hyphens
There are at least a couple of users who got Share handles with hyphens (`-`) in them because those were present in their github handles when they initially performed oauth. Pushing to `handle-with-hyphen.public.foo` doesn't work, leaving these people no way to push to Share.

Is there a good reason that we don't allow hyphens? Are there other characters that would hit this same issue?

If so, we could potentially remove the hyphens from those handles, but we need to beware of what would happen if removing the hyphen caused a collision with another user handle.

On a related note, we need to be aware that github handles can be changed. So when we are creating an account for a github handle we probably shouldn't assume that this is the only github account that has ever owned that handle, and we should make sure that there isn't a handle collision. Preventing handle collisions will need to happen anyway when we start supporting more OAuth providers.

### PR DESCRIPTION
**Pull request by ChrisPenner**
Fixes #3690 

## Overview

Currently UCM tries to parse share handles as namespace segments, but namespace segments can't have `-` in them and Share handles can.

## Implementation notes

* Swap out the first segment of a share push to parse as a share handle which allows hyphens.
* ~Allow a leading `@` to indicate the handle on pushes/pulls to share, `@unison.public.base` or w/e, we've seen at least one user try this in the past and it doesn't really hurt to support it. We'll probably change the parser again when we release projects anyways to support project shorthands like `@unison/base`. I'm mixed on this, happy to remove it if people feel it's extraneous.~

### CODE REVIEW

**Comment by hojberg** [comment]
I definitely want to support the `@` stuff, but I worry its premature and would teach people a syntax that'll change subtlety when we release projects (where I definitely thing we should allow push to project shorthands). Thoughts? Maybe it's not a real concern at all.

File: unison-share-api/src/Unison/Sync/Types.hs [hunk 1]
```diff
@@ -110,32 +110,31 @@ instance FromJSON Base64Bytes where
 newtype RepoName = RepoName {unRepoName :: Text}
   deriving newtype (Show, Eq, Ord, ToJSON, FromJSON)
 
-data Path = Path
-  { -- This is a nonempty list, where we require the first segment to be the repo name / user name / whatever,
+data ShareLocation = ShareLocation
```
Comment (mitchellwrosen) [inline unison-share-api/src/Unison/Sync/Types.hs]: I'm not totally sure the `ShareUserHandle` should be in the sync API types - I think we were trying to keep the API server-agnostic. You can see in the comment below that the `NonEmpty Text` may ideally be a `[Text]` to allow for servers to just present a codebase directly (without a "user" indirection). Could `Unison.Sync.Types.Path` remain as-is?

**Comment by ceedubs** [comment]
How does this relate to `RemoteMapping` resolution? For example if I have `myuser = "my-user"` in my config then does `.myuser.public.mylib.main> push` do the right thing?

File: unison-share-api/src/Unison/Sync/Types.hs (hunk 1 above)
Comment (ChrisPenner) [reply unison-share-api/src/Unison/Sync/Types.hs]: Hrmm, I think if we want to be agnostic about server paths we would probably want to lean into that and just send a single `Text` then right?

Ultimately UCM will probably want to know about both projects and users as a matter of convenience when dealing with syncing projects, so I think we might be fooling ourselves if we try to ignore it, but could probably put it off a bit longer. Splitting up this type isn't necessary for this change, so I could revert that part, but if it's ever cast into a Unison Path it will be an invalid one, and this was already happening in the output layer, so I figured it was safest to split it into a separate type so that nobody would accidentally assume that a `Share.Path` was a valid `Unison.Path` yknow?

Comment (aryairani) [reply unison-share-api/src/Unison/Sync/Types.hs]: Let's leave the API as `NonEmpty Text` or `[Text]` for now (nobody should accidentally assume that a `NonEmpty Text` is a valid `Unison.Path` either), and then parse that API type to some client-specific or server-specific data structure as needed.

**Comment by aryairani** [comment]
I don't feel strongly either way about supporting the `@` syntax in this PR, but note that it does feel extraneous and having fewer changes means faster merges IMO. @hojberg please make a final call on this.

**Comment by ChrisPenner** [comment]
@ceedubs  Yup! Works in my local testing 👍🏼

**Comment by ChrisPenner** [comment]
Okay, I removed the `@` syntax, and reverted the changes to the type, ready for a re-review @aryairani  @mitchellwrosen

File: parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs [hunk 2]
```diff
@@ -117,7 +120,7 @@ data ReadGitRemoteNamespace = ReadGitRemoteNamespace
 
 data ReadShareRemoteNamespace = ReadShareRemoteNamespace
   { server :: ShareCodeserver,
-    repo :: Text,
+    repo :: ShareUserHandle,
```
Comment (aryairani) [inline parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs:123]: question: this name "repo" is baked into json somewhere, right?

**Review by aryairani — APPROVED** [review]
lgtm, thanks @ChrisPenner

File: parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs (hunk 2 above)
Comment (ChrisPenner) [reply parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs:123]: I don't believe so, AFAIK we prepend it to the `path` parameter on sync requests.
