### PR TITLE
Don't crash when printing types with higher-rank fields.

### LINKED ISSUE #2849: Rehash-migration pretty-printing fails for constructors with polymorphic fields
```
structural type Foo = Foo (forall a . a -> a)
```
Then just `add` and then `view Foo` to trigger the error.

```
Encountered Exception: Failed to typecheck record field: User "up.Random.RNG._.set"
CallStack (from HasCallStack):
  error, called at src/Unison/DeclPrinter.hs:152:36 in unison-parser-typechecker-0.0.0-LZIUVczRl7wJ89oxDaccfj:Unison.DeclPrinter
```

In the rehash migration branch, types are now incorporated into term hashes. This is good and expected, but it means that our trick for detecting whether to use record accessor syntax now has to run type inference of the generated record accessors.

Since higher rank types are not inferred, this causes an inference failure during pretty-printing. The fix is as simple as just bailing on using record syntax if the field accessor doesn't typecheck, at least until https://github.com/unisonweb/unison/issues/498 can be addressed. But #498 is a bigger deal than it seems so I wouldn't make that critical path.

@aryairani not sure who best person is for this, but forwarding to you to decide. :)

### PR DESCRIPTION
**Pull request by ChrisPenner**
## Overview

fixes #2849 

Now that we typecheck record fields to get their hashes, we added a failure case when we can't properly typecheck the fields. It turns out that higher-rank fields trigger that error case, but it's acceptable to simply skip fetching field-names in that case since records aren't supported for higher-rank fields at the moment anyways.

Transcript:

    ```unison:hide
    structural type HigherRanked = HigherRanked (forall a. a -> a)
    ```

    We should be able to add and view records with higher-rank fields.

    ```ucm
    .higher_ranked> add
    .higher_ranked> view HigherRanked
    ```

### Old behaviour:

```
unison: Failed to typecheck record field: User "HigherRanked._.set"
CallStack (from HasCallStack):
  error, called at src/Unison/DeclPrinter.hs:152:36 in unison-parser-typechecker-0.0.0-3BUf37b1GA08ZzhhUKJgym:Unison.DeclPrinter
higher-rank.md EXCEPTION!!!: callCommand: /Users/cpenner/dev/unison-trunk/.stack-work/install/x86_64-osx/927e170d2a97df40cec5690e18a9496b9598d494d02c3ae16f7d0d2bc6c9948c/8.10.7/bin/unison transcript unison-src/transcripts/higher-rank.md (exit 1): failed
```

### New behaviour:

    ```ucm
    .higher_ranked> add

      ⍟ I've added these definitions:
      
        structural type HigherRanked

    .higher_ranked> view HigherRanked

      structural type HigherRanked = HigherRanked (∀ a. a -> a)

    ```

## Implementation notes

Rather than `error`, we simply return `Nothing` indicating that field names could not be found.

## Test coverage

Added a regression transcript.

### CODE REVIEW

**Review by pchiusano — APPROVED** [review]
Great!

**Review by ceedubs — APPROVED** [review]
I see some failures in the build, but I've verified that this resolves the issue that was preventing me from working in the migrated version of our code! Thank you @ChrisPenner!

```
  5 FAILED (failed scopes below)
    "create-author.md"
    "deleteReplacements.md"
    "diff-namespace.md"
    "resolve.md"
    "tls.md"

  To rerun with same random seed:

    EasyTest.rerun 8514260692059476680
    EasyTest.rerunOnly 8514260692059476680 "create-author.md"
```

**Comment by ChrisPenner** [comment]
@ceedubs  glad to hear it!

Yeah those failures are currently expected on the migration branch due to hash-mismatches. We'll fix them before we merge back into trunk 👍🏼

File: parser-typechecker/src/Unison/DeclPrinter.hs [hunk 1]
```diff
@@ -133,55 +133,60 @@ prettyDataDecl (PrettyPrintEnvDecl unsuffixifiedPPE suffixifiedPPE) r name dd =
...
+      typecheckingEnv =
+        Typechecker.Env
+          { Typechecker._ambientAbilities = mempty,
+            Typechecker._typeLookup = typeLookup,
+            Typechecker._termsByShortname = mempty
+          }
+  accessorsWithTypes :: [(v, Term.Term v (), Type.Type v ())] 
+    <- for accessors \(v, trm) ->
+         case Result.result (Typechecker.synthesize typecheckingEnv trm) of
+           Nothing -> Nothing
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/DeclPrinter.hs:169]: This `Nothing` replaces the `error` we were encountering.

The rest of the "changes" are mostly just noise from reformatting into do-notation.

File: parser-typechecker/src/Unison/DeclPrinter.hs [hunk 2]
```diff
@@ -133,55 +133,60 @@ prettyDataDecl (PrettyPrintEnvDecl unsuffixifiedPPE suffixifiedPPE) r name dd =
...
-  _ -> Nothing
+fieldNames ::
+  forall v a.
+  Var v =>
+  PrettyPrintEnv ->
+  Reference ->
+  HashQualified Name ->
+  DataDeclaration v a ->
+  Maybe [HashQualified Name]
+fieldNames env r name dd = do
```
Comment (ChrisPenner) [inline parser-typechecker/src/Unison/DeclPrinter.hs:144]: Most of the changes here are just re-formatting from a pure function into `Maybe` do-notation so I can easily fail the whole computation on a bad typecheck. I've noted the primary change with a comment.

**Review by aryairani — APPROVED** [review]
