### PR TITLE
Fix incorrect calculation of list of constructor ids for types with 0 constructors

### LINKED ISSUE #3292: Opening up `Void` by hash generates an error
Steps to reproduce: 

Go to: https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/terms/Void/absurd

Click on `Void` there in the type signature.

This seems to crash Share, bringing it down until the container gets restarted (about 30s or so).

Oddly enough visiting https://share.unison-lang.org/@unison/code/latest/namespaces/public/base/latest/;/types/Void (loading it by name) works totally fine.

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This PR fixes an incorrect enumeration of constructor ids for types with 0 constructors.

Previously, we'd enumerate `[0, 1, ..., maxBound :: Word64]` instead of `[]`.

Fixes #3292

### CODE REVIEW

**Review by pchiusano — APPROVED** [review]
Nice!

This doesn't affect hashing, does it?

**Comment by mitchellwrosen** [comment]
It doesn't affect hashing, no

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs [hunk 1]
```diff
@@ -979,13 +979,16 @@ declReferentsByPrefix b32prefix pos cid = do
       h <- Q.expectPrimaryHashByObjectId oId
       let test :: ConstructorId -> Bool
           test = maybe (const True) (==) cid
-          cids = [cid | cid <- [0 :: ConstructorId .. ctorCount - 1], test cid]
+          cids =
+            if ctorCount == 0
+              then []
+              else [cid | cid <- [0 :: ConstructorId .. fromIntegral ctorCount - 1], test cid]
       pure (h, pos, dt, cids)
```
Comment (aryairani) [inline codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs]: Let's get rid of the `- 1` altogether; though I see that it is hairy due to the `Maybe ConstructorId`.
```suggestion
          cids = case cid of
            Nothing -> take ctorCount [0 :: ConstructorId ..]
            Just cid -> if fromIntegral cid < ctorCount then [cid] else []
      pure (h, pos, dt, cids)
```

**Review by aryairani — APPROVED** [review]
I proposed a change without testing it, but otherwise looks good to me, thanks!

File: codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs (hunk 1 above)
Comment (mitchellwrosen) [reply codebase2/codebase-sqlite/U/Codebase/Sqlite/Operations.hs]: cool, I applied this suggestion

**Review by ChrisPenner — APPROVED** [review]
Looks good, we should also investigate why this exception isn't being properly caught and handled in the enlil server, an exception shouldn't crash the whole server 😬

**Comment by mitchellwrosen** [comment]
@ChrisPenner I'm not sure there is an exception here, just runaway CPU usage

**Comment by pchiusano** [comment]
> runaway CPU usage

It's runaway memory usage too, right? There's not much you can do to recover from that, it's not the sort of thing you can  catch and just keep going.

**Comment by mitchellwrosen** [comment]
> It's runaway memory usage too, right?

Yeah, that too 😛

**Comment by ChrisPenner** [comment]
Oh snap, I didn't realize it was enumerating every `Word`; I assumed it was just throwing an exception on an out-of-bounds index or something haha.
